$ErrorActionPreference = 'Stop'

function Fail([string]$Message) {
  Write-Error "[FAIL] $Message"
  exit 1
}

function Check-Contains([string]$File, [string]$Pattern, [string]$Message) {
  $content = Get-Content -Raw -LiteralPath $File
  if (-not [regex]::IsMatch($content, $Pattern)) {
    Fail $Message
  }
}

function Check-NotContains([string]$File, [string]$Pattern, [string]$Message) {
  $content = Get-Content -Raw -LiteralPath $File
  if ([regex]::IsMatch($content, $Pattern)) {
    Fail $Message
  }
}

function Check-NotExactLine([string]$File, [string]$Exact, [string]$Message) {
  $lines = Get-Content -LiteralPath $File
  if ($lines -contains $Exact) {
    Fail $Message
  }
}

foreach ($script in @('freedom.sh', 'vps_init_tool.sh', 'xray-1stream-dat.sh')) {
  if (-not (Test-Path -LiteralPath $script)) {
    Fail "missing script: $script"
  }
}

$vpsCount = @(Get-ChildItem -File -Filter 'vps_init_tool*.sh').Count
if ($vpsCount -ne 1) {
  Fail "expected exactly one vps_init_tool*.sh, found $vpsCount"
}

Check-Contains 'vps_init_tool.sh' 'TOOL_VERSION="1\.0\.4"' 'vps_init_tool.sh version drifted'
Check-NotContains 'vps_init_tool.sh' '3x-ui|x-ui|1stream\.dat' 'vps_init_tool.sh must stay focused on generic VPS initialization'
Check-Contains 'vps_init_tool.sh' 'handle_cli\(\)' 'vps_init_tool.sh missing CLI dispatcher'
Check-Contains 'vps_init_tool.sh' 'Missing value for --lang' 'vps_init_tool.sh CLI must report a missing --lang value'
Check-Contains 'vps_init_tool.sh' 'Missing value for --ports' 'vps_init_tool.sh CLI must report a missing --ports value'
Check-Contains 'vps_init_tool.sh' 'Only one command may be specified' 'vps_init_tool.sh CLI must reject multiple commands'
Check-Contains 'vps_init_tool.sh' 'original_args="\$[*]"' 'vps_init_tool.sh CLI logging must preserve original arguments before shifting'
Check-Contains 'vps_init_tool.sh' 'log_action "cli" "command=\$cmd args=\$original_args"' 'vps_init_tool.sh CLI log must use preserved original arguments'
Check-Contains 'vps_init_tool.sh' 'local cmd="" original_args="\$[*]" rc=0' 'vps_init_tool.sh CLI must track command return code'
Check-Contains 'vps_init_tool.sh' 'set \+e' 'vps_init_tool.sh CLI must disable errexit while capturing command rc'
Check-Contains 'vps_init_tool.sh' '\(\s+set -e\s+case "\$cmd" in' 'vps_init_tool.sh CLI commands must run in an errexit-enabled subshell'
Check-Contains 'vps_init_tool.sh' 'log_action "cli" "command=\$cmd complete rc=\$rc"' 'vps_init_tool.sh CLI completion log must include rc'
Check-Contains 'vps_init_tool.sh' 'exit "\$rc"' 'vps_init_tool.sh CLI must exit with captured rc'
Check-NotExactLine 'vps_init_tool.sh' '  log_action "cli" "command=$cmd complete"' 'vps_init_tool.sh CLI completion log must not omit rc'
Check-Contains 'vps_init_tool.sh' 'LOG_FILE=' 'vps_init_tool.sh missing operation log file setting'
Check-Contains 'vps_init_tool.sh' 'log_action\(\)' 'vps_init_tool.sh missing operation logger'
Check-Contains 'vps_init_tool.sh' 'restore_managed_file\(\)' 'vps_init_tool.sh missing managed configuration rollback helper'
Check-Contains 'vps_init_tool.sh' 'normalize_yes_no\(\)' 'vps_init_tool.sh missing y/n normalization helper'
Check-Contains 'vps_init_tool.sh' 'input_yes_no\(\)' 'vps_init_tool.sh missing y/n compatible yes/no prompt helper'
Check-Contains 'vps_init_tool.sh' 'normalize_password_policy\(\)' 'vps_init_tool.sh missing y/n compatible SSH password policy helper'
Check-Contains 'vps_init_tool.sh' 'APT_LOCK_TIMEOUT=' 'vps_init_tool.sh missing apt lock timeout setting'
Check-Contains 'vps_init_tool.sh' 'APT_RETRIES=' 'vps_init_tool.sh missing apt retry setting'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry\(\)' 'vps_init_tool.sh missing apt retry helper'
Check-Contains 'vps_init_tool.sh' 'DPkg::Lock::Timeout=' 'vps_init_tool.sh apt operations must wait for dpkg locks'
Check-Contains 'vps_init_tool.sh' 'errexit_was_set=0' 'vps_init_tool.sh apt retry must preserve errexit state'
Check-Contains 'vps_init_tool.sh' 'case "\$-" in' 'vps_init_tool.sh apt retry must inspect shell option state'
Check-Contains 'vps_init_tool.sh' '\*e\*\) errexit_was_set=1' 'vps_init_tool.sh apt retry must detect errexit'
Check-Contains 'vps_init_tool.sh' '\[ "\$errexit_was_set" -eq 1 \] && set -e' 'vps_init_tool.sh apt retry must restore errexit'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry update' 'vps_init_tool.sh apt update must use retry helper'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry install -y "\$@"' 'vps_init_tool.sh apt install must use retry helper'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry update \|\| return 1' 'vps_init_tool.sh apt update failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'apt_update_once \|\| return 1' 'vps_init_tool.sh apt install must stop when apt update fails'
Check-Contains 'vps_init_tool.sh' 'if \[ "\$max_by_disk_mb" -lt 512 \]; then echo "0M"; return 0; fi' 'vps_init_tool.sh must skip swapfile recommendation when disk space is too low'
Check-Contains 'vps_init_tool.sh' 'valid_size_mb_gb\(\)' 'vps_init_tool.sh missing size validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_uint_range\(\)' 'vps_init_tool.sh missing numeric range validation helper'
Check-Contains 'vps_init_tool.sh' 'Invalid swapfile size' 'vps_init_tool.sh must reject invalid swapfile sizes'
Check-Contains 'vps_init_tool.sh' 'sysctl -p /etc/sysctl\.d/99-memory-tuning\.conf' 'vps_init_tool.sh must apply and validate its memory sysctl file directly'
Check-Contains 'vps_init_tool.sh' 'sysctl -p /etc/sysctl\.d/90-bbr\.conf' 'vps_init_tool.sh must apply and validate its BBR sysctl file directly'
Check-Contains 'vps_init_tool.sh' 'sysctl -p /etc/sysctl\.d/99-proxy-tuning\.conf' 'vps_init_tool.sh must apply and validate its proxy sysctl file directly'
Check-Contains 'vps_init_tool.sh' 'if ! sysctl -p /etc/sysctl\.d/99-memory-tuning\.conf >/dev/null; then' 'vps_init_tool.sh memory sysctl failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! sysctl -p /etc/sysctl\.d/90-bbr\.conf >/dev/null; then' 'vps_init_tool.sh BBR sysctl failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! sysctl -p /etc/sysctl\.d/99-proxy-tuning\.conf >/dev/null; then' 'vps_init_tool.sh proxy sysctl failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'restore_managed_file "\$config_file" "\$config_backup"' 'vps_init_tool.sh persistent configuration failures must restore the previous file'
Check-NotContains 'vps_init_tool.sh' 'sysctl --system >/dev/null \|\| true' 'vps_init_tool.sh must not hide sysctl application failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart systemd-zram-setup@zram0\.service 2>/dev/null \|\| systemctl start systemd-zram-setup@zram0\.service 2>/dev/null \|\| true' 'vps_init_tool.sh must not hide zram-generator activation failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart zramswap\.service 2>/dev/null \|\| systemctl restart zram-config\.service 2>/dev/null \|\| true' 'vps_init_tool.sh must not hide zram-tools activation failures'
Check-Contains 'vps_init_tool.sh' '--baseline' 'vps_init_tool.sh missing low-risk baseline CLI'
Check-Contains 'vps_init_tool.sh' '--preflight' 'vps_init_tool.sh missing read-only preflight CLI'
Check-Contains 'vps_init_tool.sh' 'preflight_check\(\)' 'vps_init_tool.sh missing read-only preflight helper'
Check-Contains 'vps_init_tool.sh' '--preflight\) preflight_check; exit 0 ;;' 'vps_init_tool.sh preflight must run before root-only CLI gates'
Check-Contains 'vps_init_tool.sh' 'low_risk_baseline "cli"' 'vps_init_tool.sh CLI baseline must use explicit cli mode'
Check-NotExactLine 'vps_init_tool.sh' '  setup_swapfile || true' 'vps_init_tool.sh low-risk baseline must not recreate swapfile automatically'
Check-NotExactLine 'vps_init_tool.sh' '  setup_zram || true' 'vps_init_tool.sh low-risk baseline must not reconfigure ZRAM automatically'
Check-Contains 'vps_init_tool.sh' 'Baseline completed with' 'vps_init_tool.sh baseline must report partial failures'
Check-Contains 'vps_init_tool.sh' 'return 1' 'vps_init_tool.sh baseline must be able to return failure'
Check-Contains 'vps_init_tool.sh' '--ufw-cf-sync' 'vps_init_tool.sh missing Cloudflare UFW sync CLI'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_STATE_FILE=' 'vps_init_tool.sh missing Cloudflare UFW state file'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_LOCK_FILE=' 'vps_init_tool.sh missing Cloudflare UFW lock file'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_LOCK_TIMEOUT=' 'vps_init_tool.sh missing Cloudflare UFW lock timeout'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_LOCK_FD=""' 'vps_init_tool.sh Cloudflare UFW lock fd must be held globally'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_acquire\(\)' 'vps_init_tool.sh missing Cloudflare UFW lock helper'
Check-Contains 'vps_init_tool.sh' 'flock is required for safe Cloudflare UFW sync' 'vps_init_tool.sh must fail safely when flock is unavailable'
Check-Contains 'vps_init_tool.sh' 'exec \{UFW_CF_LOCK_FD\}>"\$UFW_CF_LOCK_FILE"' 'vps_init_tool.sh Cloudflare UFW lock must use a dynamic fd held globally'
Check-Contains 'vps_init_tool.sh' 'flock -w "\${UFW_CF_LOCK_TIMEOUT:-120}" "\$UFW_CF_LOCK_FD"' 'vps_init_tool.sh Cloudflare UFW sync must use flock with timeout'
Check-Contains 'vps_init_tool.sh' 'exec \{UFW_CF_LOCK_FD\}>&- 2>/dev/null \|\| true' 'vps_init_tool.sh must close Cloudflare UFW lock fd if flock acquisition fails'
Check-NotContains 'vps_init_tool.sh' 'exec 9>"\$UFW_CF_LOCK_FILE"' 'vps_init_tool.sh Cloudflare UFW lock must not reserve fixed fd 9'
Check-NotContains 'vps_init_tool.sh' 'local lock_fd' 'vps_init_tool.sh Cloudflare UFW lock fd must not be local to acquire helper'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_release\(\)' 'vps_init_tool.sh missing Cloudflare UFW lock release helper'
Check-Contains 'vps_init_tool.sh' 'flock -u "\$UFW_CF_LOCK_FD"' 'vps_init_tool.sh Cloudflare UFW lock release must unlock fd'
Check-Contains 'vps_init_tool.sh' 'exec \{UFW_CF_LOCK_FD\}>&-' 'vps_init_tool.sh Cloudflare UFW lock release must close fd'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_release' 'vps_init_tool.sh Cloudflare UFW sync must release lock explicitly'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_acquire || return 1' 'vps_init_tool.sh Cloudflare UFW sync must acquire lock before mutating rules'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_sync_cleanup\(\)' 'vps_init_tool.sh missing Cloudflare UFW sync RETURN cleanup helper'
Check-Contains 'vps_init_tool.sh' 'cleanup_files "\$@"' 'vps_init_tool.sh Cloudflare UFW cleanup helper must use explicit path arguments'
Check-Contains 'vps_init_tool.sh' 'local ports desired="" current="" adds="" deletes="" state_tmp=""' 'vps_init_tool.sh Cloudflare UFW temp paths must initialize empty before cleanup trap'
Check-Contains 'vps_init_tool.sh' 'ufw_ensure_ssh_access \|\| \{ ufw_cf_sync_cleanup "\$desired"' 'vps_init_tool.sh must cleanup Cloudflare UFW sync if SSH allow check fails'
Check-Contains 'vps_init_tool.sh' 'cf_fetch_ranges \|\| \{ ufw_cf_sync_cleanup "\$desired"' 'vps_init_tool.sh must cleanup Cloudflare UFW sync if Cloudflare ranges fetch fails'
Check-Contains 'vps_init_tool.sh' 'desired="\$\(mktemp\)" \|\| \{ ufw_cf_sync_cleanup "\$desired"' 'vps_init_tool.sh Cloudflare UFW sync must cleanup if desired temp creation fails'
Check-Contains 'vps_init_tool.sh' 'cleanup_files\(\)' 'vps_init_tool.sh missing temp-file cleanup helper'
Check-Contains 'vps_init_tool.sh' 'rm -f -- "\$@"' 'vps_init_tool.sh cleanup helper must use rm -- for path safety'
Check-Contains 'vps_init_tool.sh' 'v4_tmp="\$\(mktemp /var/lib/vps-init/cloudflare-ips-v4\.txt\.XXXXXX\)" \|\| return 1' 'vps_init_tool.sh Cloudflare v4 temp creation must fail safely'
Check-Contains 'vps_init_tool.sh' 'v6_tmp="\$\(mktemp /var/lib/vps-init/cloudflare-ips-v6\.txt\.XXXXXX\)" \|\| \{ cleanup_files "\$v4_tmp"; return 1; \}' 'vps_init_tool.sh Cloudflare v6 temp creation must cleanup v4 temp on failure'
Check-Contains 'vps_init_tool.sh' 'cleanup_files "\$v4_tmp" "\$v6_tmp"' 'vps_init_tool.sh Cloudflare range fetch must cleanup temp downloads on failure'
Check-Contains 'vps_init_tool.sh' 'if ! mv "\$v4_tmp" /var/lib/vps-init/cloudflare-ips-v4.txt; then cleanup_files "\$v4_tmp" "\$v6_tmp"; return 1; fi' 'vps_init_tool.sh must cleanup temp Cloudflare v4 file if mv fails'
Check-Contains 'vps_init_tool.sh' 'if ! mv "\$v6_tmp" /var/lib/vps-init/cloudflare-ips-v6.txt; then cleanup_files "\$v4_tmp" "\$v6_tmp"; return 1; fi' 'vps_init_tool.sh must cleanup temp Cloudflare v6 file if mv fails'
Check-NotContains 'vps_init_tool.sh' 'ufw allow proto tcp from "\$cidr" to any port "\$p" comment "cloudflare-\$p" \|\| true' 'vps_init_tool.sh must not record failed Cloudflare UFW additions as synced'
Check-NotContains 'vps_init_tool.sh' 'ufw --force delete allow proto tcp from "\$cidr" to any port "\$port" >/dev/null 2>&1 \|\| true' 'vps_init_tool.sh must not record failed Cloudflare UFW deletions as synced'
Check-Contains 'vps_init_tool.sh' 'ufw --force delete allow proto tcp from "\$cidr" to any port "\$port" comment "cloudflare-\$port"' 'vps_init_tool.sh must delete only Cloudflare UFW rules marked by this tool'
Check-Contains 'vps_init_tool.sh' 'Cloudflare UFW add failed' 'vps_init_tool.sh must report failed Cloudflare UFW additions'
Check-Contains 'vps_init_tool.sh' 'Cloudflare UFW delete failed' 'vps_init_tool.sh must report failed Cloudflare UFW deletions'
Check-Contains 'vps_init_tool.sh' 'ssh_reload_or_restart\(\)' 'vps_init_tool.sh missing SSH reload/restart helper'
Check-Contains 'vps_init_tool.sh' 'ssh_remove_hardening_fragment\(\)' 'vps_init_tool.sh missing SSH hardening rollback helper'
Check-Contains 'vps_init_tool.sh' 'ssh_restore_hardening_backup\(\)' 'vps_init_tool.sh missing SSH hardening backup restore helper'
Check-Contains 'vps_init_tool.sh' 'fragment_backup="\$BACKUP_LAST_PATH"' 'vps_init_tool.sh must retain the previous SSH hardening fragment backup path'
Check-Contains 'vps_init_tool.sh' 'ssh_restore_hardening_backup "\$fragment_backup"' 'vps_init_tool.sh must restore the previous SSH hardening fragment on failure'
Check-Contains 'vps_init_tool.sh' 'ssh_key_line_valid\(\)' 'vps_init_tool.sh missing authorized_keys line validator'
Check-Contains 'vps_init_tool.sh' 'user_has_authorized_key\(\)' 'vps_init_tool.sh missing key-login readiness helper'
Check-Contains 'vps_init_tool.sh' 'ssh_require_key_login_ready\(\)' 'vps_init_tool.sh must verify usable public keys before disabling SSH passwords'
Check-Contains 'vps_init_tool.sh' 'valid_ssh_public_key\(\)' 'vps_init_tool.sh missing SSH public key format validation helper'
Check-Contains 'vps_init_tool.sh' 'ssh-keygen -l -f' 'vps_init_tool.sh must validate SSH public keys with ssh-keygen when available'
Check-Contains 'vps_init_tool.sh' 'valid_ssh_public_key "\$key"' 'vps_init_tool.sh must validate SSH public keys before installing'
Check-Contains 'vps_init_tool.sh' 'group="\$\(id -gn "\$user" 2>/dev/null \|\| echo "\$user"\)"' 'vps_init_tool.sh must chown SSH keys using the user primary group'
Check-Contains 'vps_init_tool.sh' 'SSH_CONNECTION' 'vps_init_tool.sh must include the current SSH session port when protecting firewall access'
Check-Contains 'vps_init_tool.sh' 'ufw_ensure_ssh_access \|\| \{ ssh_restore_hardening_backup "\$fragment_backup"; return 1; \}' 'vps_init_tool.sh SSH hardening must protect current SSH ports before reload'
Check-Contains 'vps_init_tool.sh' 'SSH firewall allow failed' 'vps_init_tool.sh must abort SSH hardening if the firewall rule cannot be added'
Check-NotContains 'vps_init_tool.sh' 'if has_cmd ufw; then ufw allow "\$port/tcp" comment "SSH" \|\| true; fi' 'vps_init_tool.sh must not ignore SSH firewall allow failures'
Check-Contains 'vps_init_tool.sh' 'SSH service reload/restart failed' 'vps_init_tool.sh must report failed SSH activation'
Check-NotContains 'vps_init_tool.sh' 'PasswordAuthentication yes' 'vps_init_tool.sh must not force SSH password login on'
Check-NotContains 'vps_init_tool.sh' 'systemctl reload ssh 2>/dev/null \|\| systemctl reload sshd 2>/dev/null \|\| systemctl restart ssh 2>/dev/null \|\| systemctl restart sshd 2>/dev/null \|\| true' 'vps_init_tool.sh must not silently ignore SSH reload/restart failures'
Check-Contains 'vps_init_tool.sh' 'fail2ban-client -t' 'vps_init_tool.sh must validate Fail2ban configuration before activation'
Check-Contains 'vps_init_tool.sh' 'Fail2ban configuration test failed' 'vps_init_tool.sh must report invalid Fail2ban configuration'
Check-Contains 'vps_init_tool.sh' 'ufw status 2>/dev/null \| grep -q ''\^Status: active''' 'vps_init_tool.sh must use the UFW Fail2ban action only when UFW is active'
Check-Contains 'vps_init_tool.sh' 'valid_ip_literal\(\)' 'vps_init_tool.sh missing IP literal validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_ip_list\(\)' 'vps_init_tool.sh missing DNS server list validation helper'
Check-Contains 'vps_init_tool.sh' 'Invalid primary DNS server list' 'vps_init_tool.sh must reject invalid systemd-resolved DNS server lists'
Check-Contains 'vps_init_tool.sh' '\[ -L /etc/resolv\.conf \]' 'vps_init_tool.sh must not directly overwrite a managed resolv.conf symlink'
Check-Contains 'vps_init_tool.sh' 'dns_restore_resolved_backup\(\)' 'vps_init_tool.sh missing systemd-resolved rollback helper'
Check-NotContains 'vps_init_tool.sh' 'DNSSEC=no' 'vps_init_tool.sh must not force DNSSEC off'
Check-Contains 'vps_init_tool.sh' 'valid_systemd_size\(\)' 'vps_init_tool.sh missing journald size validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_systemd_timespan\(\)' 'vps_init_tool.sh missing journald retention validation helper'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart systemd-journald \|\| true' 'vps_init_tool.sh must not hide journald restart failures'
Check-NotContains 'vps_init_tool.sh' 'backup_path .* >/dev/null \|\| true' 'vps_init_tool.sh must not overwrite managed configuration after a failed backup'
Check-NotContains 'vps_init_tool.sh' 'ufw limit "\$p/tcp" comment "rate-limit-ssh" \|\| true' 'vps_init_tool.sh must not hide SSH rate-limit rule failures'
Check-NotContains 'vps_init_tool.sh' 'fail2ban-client set "\$jail" unbanip "\$ip" \|\| true' 'vps_init_tool.sh must not hide Fail2ban unban failures'
Check-Contains 'vps_init_tool.sh' 'valid_ip_literal "\$ip"' 'vps_init_tool.sh must validate Fail2ban unban IP addresses'
Check-Contains 'vps_init_tool.sh' 'Invalid IP to unban' 'vps_init_tool.sh must report invalid Fail2ban unban IP addresses'

Check-Contains 'freedom.sh' 'SCRIPT_VERSION="v9\.11-xray"' 'freedom.sh version drifted'
Check-Contains 'freedom.sh' 'DEFAULT_SNI="v1-dy\.ixigua\.com"' 'freedom.sh default SNI drifted'
Check-Contains 'freedom.sh' 'ensure_xray_installed\(\)' 'freedom.sh must install/configure Xray-core only'
Check-Contains 'freedom.sh' 'write_xray_config\(\)' 'freedom.sh missing Xray config writer'
Check-Contains 'freedom.sh' 'preflight_check\(\)' 'freedom.sh missing read-only preflight check'
Check-Contains 'freedom.sh' 'validate_domain_name\(\)' 'freedom.sh missing SNI domain validator'
Check-Contains 'freedom.sh' 'probe_sni_domain\(\)' 'freedom.sh missing SNI reachability probe'
Check-Contains 'freedom.sh' 'openssl s_client' 'freedom.sh SNI probe must use openssl s_client for TLS capability checks'
Check-Contains 'freedom.sh' '-tls1_3' 'freedom.sh SNI probe must explicitly test TLS 1.3 support'
Check-Contains 'freedom.sh' '-alpn h2,http/1\.1' 'freedom.sh SNI probe must explicitly test ALPN/H2 support'
Check-Contains 'freedom.sh' 'ALPN protocol: h2' 'freedom.sh SNI probe must recognize negotiated HTTP/2'
Check-Contains 'freedom.sh' 'SNI_CHECK=' 'freedom.sh missing SNI check toggle'
Check-Contains 'freedom.sh' '--skip-sni-check' 'freedom.sh missing SNI check bypass option'
Check-Contains 'freedom.sh' 'validate_link_host\(\)' 'freedom.sh missing server/link host validator'
Check-Contains 'freedom.sh' 'host:port is not accepted' 'freedom.sh must reject server host:port inputs'
Check-Contains 'freedom.sh' 'validate_domain_name "\$host"' 'freedom.sh server host validator must accept only valid domain names for hostname input'
Check-Contains 'freedom.sh' 'ip_to_int "\$host"' 'freedom.sh server host validator must validate IPv4 input'
Check-Contains 'freedom.sh' 'validate_ipv6_literal\(\)' 'freedom.sh missing IPv6 literal validator'
Check-Contains 'freedom.sh' 'local -a left_parts right_parts parts' 'freedom.sh IPv6 validator must keep arrays local'
Check-Contains 'freedom.sh' 'validate_ipv6_literal "\$host"' 'freedom.sh server host validator must use IPv6 literal validator'
Check-Contains 'freedom.sh' 'return 1 # malformed hostname' 'freedom.sh server host validator must reject malformed hostnames'
Check-Contains 'freedom.sh' 'ip_to_int\(\)' 'freedom.sh missing IPv4 integer conversion helper'
Check-Contains 'freedom.sh' 'ip_in_range\(\)' 'freedom.sh missing IPv4 CIDR range helper'
Check-Contains 'freedom.sh' 'ip_in_range "\$ip_num"' 'freedom.sh private/local IPv4 detection must use numeric ranges'
Check-Contains 'freedom.sh' 'is_private_or_local_ip\(\)' 'freedom.sh missing private/local IP detector'
Check-Contains 'freedom.sh' 'auto_detected_server=1' 'freedom.sh must track auto-detected server address'
Check-Contains 'freedom.sh' 'is_private_or_local_ip "\$SERVER_IP"' 'freedom.sh must reject private/local auto-detected server addresses'
Check-Contains 'freedom.sh' '2001:db8' 'freedom.sh must treat IPv6 documentation addresses as non-public'
Check-Contains 'freedom.sh' 'ff\*' 'freedom.sh must treat IPv6 multicast addresses as non-public'
Check-Contains 'freedom.sh' 'secure_config_permissions\(\)' 'freedom.sh missing secure config permissions helper'
Check-Contains 'freedom.sh' 'download_and_run_installer\(\)' 'freedom.sh missing safer installer runner'
Check-Contains 'freedom.sh' '--xray-encryption' 'freedom.sh missing Xray encryption CLI option'
Check-Contains 'freedom.sh' 'XRAY_ENCRYPTION_CHOICE="\$\{FREEDOM_XRAY_ENCRYPTION:-x25519\}"' 'freedom.sh must default VLESS Encryption auth to X25519'
Check-Contains 'freedom.sh' 'extract_vlessenc_value\(\)' 'freedom.sh must select X25519 or ML-KEM-768 auth from xray vlessenc output'
Check-Contains 'freedom.sh' 'alg="X25519"' 'freedom.sh must support X25519 auth selection'
Check-Contains 'freedom.sh' 'alg="ML-KEM-768"' 'freedom.sh must support ML-KEM-768 auth selection'
Check-Contains 'freedom.sh' 'extract_vlessenc_value "\$out" "\$alg" "decryption"' 'freedom.sh must extract selected auth decryption from xray vlessenc output'
Check-Contains 'freedom.sh' 'extract_vlessenc_value "\$out" "\$alg" "encryption"' 'freedom.sh must extract selected auth encryption from xray vlessenc output'
Check-Contains 'freedom.sh' 'xray_tls_ping_probe\(\)' 'freedom.sh missing official xray tls ping SNI probe'
Check-Contains 'freedom.sh' 'tls ping "\$host"' 'freedom.sh SNI probe should prefer official xray tls ping'
Check-Contains 'freedom.sh' 'generate_spider_x\(\)' 'freedom.sh missing randomized REALITY spiderX generator'
Check-Contains 'freedom.sh' 'token="\$\(gen_uuid' 'freedom.sh spiderX randomness should prefer official xray uuid generator'
Check-Contains 'freedom.sh' 'SPIDER_X=' 'freedom.sh missing spiderX state'
Check-Contains 'freedom.sh' 'encoded_spider_x="\$\(url_encode "\$SPIDER_X"\)"' 'freedom.sh share link must URL-encode generated spiderX'
Check-Contains 'freedom.sh' 'spx=\$\{encoded_spider_x\}' 'freedom.sh share link must use generated spiderX'
Check-Contains 'freedom.sh' 'network: "raw"' 'freedom.sh REALITY transport should use official raw network'
Check-Contains 'freedom.sh' 'type=raw' 'freedom.sh share link must use raw network'
Check-NotContains 'freedom.sh' 'network: "tcp"' 'freedom.sh should not use legacy tcp network spelling for REALITY'
Check-NotContains 'freedom.sh' 'type=tcp' 'freedom.sh share link should not use legacy tcp type'
Check-NotContains 'freedom.sh' 'spx=%2F' 'freedom.sh should not pin spiderX to root path'
Check-Contains 'freedom.sh' '--check, --preflight' 'freedom.sh missing read-only preflight CLI option'
Check-Contains 'freedom.sh' 'clear_screen\(\)' 'freedom.sh missing non-interactive clear guard'
Check-Contains 'freedom.sh' 'verify_service_port_listening\(\)' 'freedom.sh missing post-restart port listener verification'
Check-Contains 'freedom.sh' 'verify_service_port_listening' 'freedom.sh restart flow must verify the service port is listening'
Check-Contains 'freedom.sh' 'not listening on TCP port' 'freedom.sh must report missing post-restart listener'
Check-Contains 'freedom.sh' 'Xray config install failed' 'freedom.sh must handle config install failures explicitly'
Check-Contains 'freedom.sh' 'if ! install -m 600 "\$tmp" "\$CONFIG_PATH"; then' 'freedom.sh config install must not rely on errexit'
Check-Contains 'freedom.sh' 'fallback: xray -test -config' 'freedom.sh config validation must preserve fallback test diagnostics'
Check-Contains 'freedom.sh' 'usage_error\(\)' 'freedom.sh missing CLI usage error helper'
Check-Contains 'freedom.sh' 'require_option_value\(\)' 'freedom.sh missing CLI option value validator'
Check-Contains 'freedom.sh' 'require_option_value "--sni"' 'freedom.sh CLI must validate --sni values'
Check-Contains 'freedom.sh' 'require_option_value "--xray-encryption"' 'freedom.sh CLI must validate --xray-encryption values'
Check-Contains 'freedom.sh' 'validate_generated_config "\$tmp"' 'freedom.sh must validate generated temp config before installing it'
Check-Contains 'freedom.sh' '"\$BIN" run -test -c "\$config_file"' 'freedom.sh temp config validation must use xray run -test before install'
Check-Contains 'freedom.sh' 'H2 is recommended, not mandatory' 'freedom.sh must treat missing H2 as a warning instead of a hard failure'
Check-NotContains 'freedom.sh' '\[\[ "\$tls_ok" -ne 1 \|\| "\$h2_ok" -ne 1 \]\]' 'freedom.sh must not require H2 for SNI usability'
Check-Contains 'freedom.sh' '\{"type":"field","ip":\["geoip:private"\],"outboundTag":"block"\}' 'freedom.sh route must block private IP first'
Check-Contains 'freedom.sh' '\{"type":"field","protocol":\["bittorrent"\],"outboundTag":"block"\}' 'freedom.sh route must block bittorrent traffic through Xray'
Check-Contains 'freedom.sh' '\{"type":"field","domain":\["geosite:geolocation-!cn"\],"outboundTag":"direct"\}' 'freedom.sh route must direct known non-CN domains before CN blocks'
Check-Contains 'freedom.sh' '\{"type":"field","domain":\["geosite:cn"\],"outboundTag":"block"\}' 'freedom.sh route must block CN domains'
Check-Contains 'freedom.sh' '\{"type":"field","ip":\["geoip:cn"\],"outboundTag":"block"\}' 'freedom.sh route must block CN IP'
Check-NotContains 'freedom.sh' '\{"type":"field","ip":\["geoip:private","geoip:cn"\],"outboundTag":"block"\}' 'freedom.sh route must keep private and CN IP blocks ordered separately'

Check-NotContains 'freedom.sh' 'sing-box|singbox|--kernel|FREEDOM_KERNEL|write_singbox_config|install_singbox_official|gen_reality_keys_singbox|choose_kernel' 'freedom.sh still contains sing-box/core-selection support'
Check-NotContains 'freedom.sh' '> "\$CONFIG_PATH"' 'freedom.sh must write config atomically instead of truncating config path directly'
Check-NotContains 'freedom.sh' 'chmod 644 "\$CONFIG_PATH"' 'freedom.sh must not make Xray config world-readable'
Check-NotContains 'freedom.sh' '/tmp/freedom-' 'freedom.sh must not use predictable /tmp log paths'
Check-NotContains 'freedom.sh' 'curl .*[|] sh' 'freedom.sh must not pipe installer downloads to sh'
Check-NotContains 'freedom.sh' 'bash -c "\$\(curl' 'freedom.sh must not execute downloaded installer inline'
Check-NotContains 'freedom.sh' 'xargs -r rm -f' 'freedom.sh backup cleanup must not use ls/xargs deletion'

$bashCandidates = @(Get-Command bash -ErrorAction SilentlyContinue | Where-Object { $_.Source -notlike '*\System32\bash.exe' -and $_.Source -notlike '*\WindowsApps\bash.exe' })
if ($bashCandidates.Count -gt 0) {
  & $bashCandidates[0].Source verify.sh
  if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
  }
} else {
  Write-Host '[WARN] usable bash not found; skipped bash syntax checks.'
}

Write-Host '[OK] verification passed'
