$ErrorActionPreference = 'Stop'

function Fail([string]$Message) {
  Write-Error "[FAIL] $Message"
  exit 1
}

function Check-Contains([string]$File, [string]$Pattern, [string]$Message) {
  $content = Get-Content -Raw -LiteralPath $File
  if (-not [regex]::IsMatch($content, $Pattern)) {
    Fail $Message
  }
}

function Check-NotContains([string]$File, [string]$Pattern, [string]$Message) {
  $content = Get-Content -Raw -LiteralPath $File
  if ([regex]::IsMatch($content, $Pattern)) {
    Fail $Message
  }
}

function Check-AsciiOnly([string]$File, [string]$Message) {
  foreach ($byte in [System.IO.File]::ReadAllBytes((Resolve-Path -LiteralPath $File))) {
    if ($byte -gt 127) {
      Fail $Message
    }
  }
}

function Check-NotExactLine([string]$File, [string]$Exact, [string]$Message) {
  $lines = Get-Content -LiteralPath $File
  if ($lines -contains $Exact) {
    Fail $Message
  }
}

foreach ($script in @('freedom.sh', 'vps_init_tool.sh', 'xray-1stream-dat.sh')) {
  if (-not (Test-Path -LiteralPath $script)) {
    Fail "missing script: $script"
  }
}

$vpsCount = @(Get-ChildItem -File -Filter 'vps_init_tool*.sh').Count
if ($vpsCount -ne 1) {
  Fail "expected exactly one vps_init_tool*.sh, found $vpsCount"
}

Check-Contains 'vps_init_tool.sh' 'TOOL_VERSION="1\.3\.1"' 'vps_init_tool.sh version drifted'
Check-AsciiOnly 'vps_init_tool.sh' 'vps_init_tool.sh must stay ASCII-only for portable terminal output'
Check-NotContains 'vps_init_tool.sh' '"\): \$\(current_ssh_ports\)\)"\)' 'vps_init_tool.sh must not duplicate SSH port text after m()'
Check-NotContains 'vps_init_tool.sh' '''\) before UFW changes to avoid locking you out\.' 'vps_init_tool.sh must not duplicate UFW lockout text after m()'
Check-NotContains 'vps_init_tool.sh' '"\): \$ssh_ports/tcp\."\)' 'vps_init_tool.sh must not duplicate SSH allow text after m()'
Check-NotContains 'vps_init_tool.sh' '"\) \$ssh_ports before enabling\."\)' 'vps_init_tool.sh must not duplicate UFW inactive text after m()'
Check-NotContains 'vps_init_tool.sh' '"\): \$ssh_ports, then enable UFW\."\)' 'vps_init_tool.sh must not duplicate UFW safe-init text after m()'
Check-NotContains 'vps_init_tool.sh' '"\)\. Review the output before rebooting\."\)' 'vps_init_tool.sh must not duplicate baseline failure text after m()'
Check-NotContains 'vps_init_tool.sh' '3x-ui|x-ui|1stream\.dat' 'vps_init_tool.sh must stay focused on generic VPS initialization'
Check-Contains 'vps_init_tool.sh' 'handle_cli\(\)' 'vps_init_tool.sh missing CLI dispatcher'
Check-Contains 'vps_init_tool.sh' 'package_manager_detect\(\)' 'vps_init_tool.sh missing package manager compatibility detector'
Check-Contains 'vps_init_tool.sh' 'os_support_level\(\)' 'vps_init_tool.sh missing OS support level helper'
Check-Contains 'vps_init_tool.sh' 'derivative-audit' 'vps_init_tool.sh must distinguish Debian/Ubuntu derivatives from fully supported systems'
Check-Contains 'vps_init_tool.sh' 'ID_LIKE' 'vps_init_tool.sh compatibility report must expose derivative lineage'
Check-Contains 'vps_init_tool.sh' 'doctor_report\(\)' 'vps_init_tool.sh missing read-only doctor report'
Check-Contains 'vps_init_tool.sh' 'Doctor report' 'vps_init_tool.sh doctor output should have a clear title'
Check-Contains 'vps_init_tool.sh' 'Read-only module readiness' 'vps_init_tool.sh doctor output should include module readiness'
Check-Contains 'vps_init_tool.sh' 'Recommended commands' 'vps_init_tool.sh doctor output should include command suggestions'
Check-Contains 'vps_init_tool.sh' '--doctor' 'vps_init_tool.sh missing doctor CLI'
Check-Contains 'vps_init_tool.sh' '--doctor\) doctor_report; exit 0 ;;' 'vps_init_tool.sh doctor must run before root-only gates'
Check-Contains 'vps_init_tool.sh' 'optimization_assessment\(\)' 'vps_init_tool.sh missing layered optimization assessment'
Check-Contains 'vps_init_tool.sh' 'automatic_optimize\(\)' 'vps_init_tool.sh missing safe automatic optimization entry point'
Check-Contains 'vps_init_tool.sh' 'guided_optimization\(\)' 'vps_init_tool.sh missing guided optimization workflow'
Check-Contains 'vps_init_tool.sh' 'bbr_available_readonly\(\)' 'vps_init_tool.sh missing read-only BBR availability helper'
Check-Contains 'vps_init_tool.sh' 'security_updates_fully_enabled\(\)' 'vps_init_tool.sh optimization assessment must verify the complete automatic updates state'
Check-Contains 'vps_init_tool.sh' 'Automatic optimization' 'vps_init_tool.sh assessment must expose automatic optimization tier'
Check-Contains 'vps_init_tool.sh' 'Optional optimization' 'vps_init_tool.sh assessment must expose optional optimization tier'
Check-Contains 'vps_init_tool.sh' 'Reference optimization' 'vps_init_tool.sh assessment must expose reference optimization tier'
Check-Contains 'vps_init_tool.sh' '--optimize-check' 'vps_init_tool.sh missing read-only optimization assessment CLI'
Check-Contains 'vps_init_tool.sh' '--optimize-auto' 'vps_init_tool.sh missing safe automatic optimization CLI'
Check-Contains 'vps_init_tool.sh' '--optimize-check\) optimization_assessment; exit 0 ;;' 'vps_init_tool.sh optimization assessment must run before root-only gates'
Check-Contains 'vps_init_tool.sh' '--optimize-auto\) automatic_optimize "cli" ;;' 'vps_init_tool.sh automatic optimization CLI must use explicit cli mode'
Check-Contains 'vps_init_tool.sh' 'Optimization assessment / guided setup' 'vps_init_tool.sh menu must expose guided optimization'
Check-Contains 'vps_init_tool.sh' 'apply_safe_automatic_optimizations\(\)' 'vps_init_tool.sh automatic and baseline flows must share one safe implementation'
Check-Contains 'vps_init_tool.sh' 'print_recommended_workflow\(\)' 'vps_init_tool.sh missing recommended workflow guidance'
Check-Contains 'vps_init_tool.sh' 'Recommended workflow' 'vps_init_tool.sh compatibility report should include actionable workflow guidance'
Check-Contains 'vps_init_tool.sh' 'bash vps_init_tool.sh --preflight' 'vps_init_tool.sh recommended workflow must start with preflight'
Check-Contains 'vps_init_tool.sh' 'bash vps_init_tool.sh --audit' 'vps_init_tool.sh recommended workflow must include full audit'
Check-Contains 'vps_init_tool.sh' 'bash vps_init_tool.sh --optimize-auto --yes' 'vps_init_tool.sh recommended workflow must include safe automatic optimization'
Check-Contains 'vps_init_tool.sh' 'bash vps_init_tool.sh --ssh-audit' 'vps_init_tool.sh recommended workflow must include SSH audit'
Check-Contains 'vps_init_tool.sh' 'bash vps_init_tool.sh --ufw-audit' 'vps_init_tool.sh recommended workflow must include UFW audit'
Check-Contains 'vps_init_tool.sh' 'bash vps_init_tool.sh --ufw-cf-sync --ports 80,443 --yes' 'vps_init_tool.sh recommended workflow must include Cloudflare UFW sync example'
Check-Contains 'vps_init_tool.sh' 'compatibility_report\(\)' 'vps_init_tool.sh missing read-only compatibility report'
Check-Contains 'vps_init_tool.sh' '--compat' 'vps_init_tool.sh missing compatibility report CLI'
Check-Contains 'vps_init_tool.sh' '--compat\) compatibility_report; exit 0 ;;' 'vps_init_tool.sh compatibility report must run before root-only gates'
Check-Contains 'vps_init_tool.sh' '--memory-audit' 'vps_init_tool.sh missing memory audit CLI'
Check-Contains 'vps_init_tool.sh' '--ssh-audit' 'vps_init_tool.sh missing SSH audit CLI'
Check-Contains 'vps_init_tool.sh' '--fail2ban-audit' 'vps_init_tool.sh missing Fail2ban audit CLI'
Check-Contains 'vps_init_tool.sh' '--dns-audit' 'vps_init_tool.sh missing DNS audit CLI'
Check-Contains 'vps_init_tool.sh' '--logs-audit' 'vps_init_tool.sh missing logs audit CLI'
Check-Contains 'vps_init_tool.sh' '--updates-audit' 'vps_init_tool.sh missing automatic security updates audit CLI'
Check-Contains 'vps_init_tool.sh' '--updates-enable' 'vps_init_tool.sh missing automatic security updates enable CLI'
Check-Contains 'vps_init_tool.sh' '--updates-disable' 'vps_init_tool.sh missing automatic security updates disable CLI'
Check-Contains 'vps_init_tool.sh' '--list-backups' 'vps_init_tool.sh missing backup listing CLI'
Check-Contains 'vps_init_tool.sh' '--memory-audit\) memory_report ;;' 'vps_init_tool.sh memory audit CLI must call memory_report'
Check-Contains 'vps_init_tool.sh' '--ssh-audit\) ssh_audit ;;' 'vps_init_tool.sh SSH audit CLI must call ssh_audit'
Check-Contains 'vps_init_tool.sh' '--fail2ban-audit\) fail2ban_audit ;;' 'vps_init_tool.sh Fail2ban audit CLI must call fail2ban_audit'
Check-Contains 'vps_init_tool.sh' 'require_systemd \|\| return 1' 'vps_init_tool.sh Fail2ban setup must stop early without systemd'
Check-Contains 'vps_init_tool.sh' '--dns-audit\) dns_audit ;;' 'vps_init_tool.sh DNS audit CLI must call dns_audit'
Check-Contains 'vps_init_tool.sh' '--logs-audit\) logs_audit ;;' 'vps_init_tool.sh logs audit CLI must call logs_audit'
Check-Contains 'vps_init_tool.sh' '--updates-audit\) security_updates_audit; exit 0 ;;' 'vps_init_tool.sh security updates audit must run before root-only gates'
Check-Contains 'vps_init_tool.sh' '--updates-enable\) security_updates_enable ;;' 'vps_init_tool.sh security updates enable CLI must call its module'
Check-Contains 'vps_init_tool.sh' '--updates-disable\) security_updates_disable ;;' 'vps_init_tool.sh security updates disable CLI must call its module'
Check-Contains 'vps_init_tool.sh' '--list-backups\) list_backups ;;' 'vps_init_tool.sh backup listing CLI must call list_backups'
Check-Contains 'vps_init_tool.sh' 'ufw_parse_cloudflare_ports "\$UFW_CF_PORTS" \|\| \{ red "Invalid --ports value: \$UFW_CF_PORTS"; show_help; exit 2; \}' 'vps_init_tool.sh CLI must validate --ports before running Cloudflare sync'
Check-Contains 'vps_init_tool.sh' 'comma-separated single ports only, no ranges' 'vps_init_tool.sh help must explain --ports format'
Check-Contains 'vps_init_tool.sh' 'Missing value for --lang' 'vps_init_tool.sh CLI must report a missing --lang value'
Check-Contains 'vps_init_tool.sh' 'cn currently uses English output' 'vps_init_tool.sh help must explain cn compatibility behavior'
Check-Contains 'vps_init_tool.sh' 'zh\|zh-cn\|zh_CN\|cn\|CN\|chinese\|Chinese\) echo "en" ;;' 'vps_init_tool.sh Chinese language aliases must normalize to English-safe output'
Check-NotContains 'vps_init_tool.sh' 'language_menu\(\)' 'vps_init_tool.sh must not expose a fake language switch in the interactive UI'
Check-Contains 'vps_init_tool.sh' 'ui_init\(\)' 'vps_init_tool.sh missing terminal color initialization'
Check-Contains 'vps_init_tool.sh' 'NO_COLOR' 'vps_init_tool.sh must honor the NO_COLOR convention'
Check-Contains 'vps_init_tool.sh' 'VPS_INIT_COLOR=auto\|always\|never' 'vps_init_tool.sh help must document color control'
Check-Contains 'vps_init_tool.sh' 'Missing value for --color' 'vps_init_tool.sh CLI must report a missing --color value'
Check-Contains 'vps_init_tool.sh' 'Invalid --color value' 'vps_init_tool.sh CLI must reject an invalid color mode'
Check-Contains 'vps_init_tool.sh' 'menu_item\(\)' 'vps_init_tool.sh missing reusable menu item renderer'
Check-Contains 'vps_init_tool.sh' 'menu_choice\(\)' 'vps_init_tool.sh missing validated menu input helper'
Check-Contains 'vps_init_tool.sh' 'Back \(b/q also works\)' 'vps_init_tool.sh menus must advertise keyboard navigation aliases'
Check-Contains 'vps_init_tool.sh' 'Security & Access' 'vps_init_tool.sh main navigation must group security modules'
Check-Contains 'vps_init_tool.sh' 'Memory & Performance' 'vps_init_tool.sh main navigation must group performance modules'
Check-Contains 'vps_init_tool.sh' 'Logs & Maintenance' 'vps_init_tool.sh main navigation must group maintenance modules'
Check-Contains 'vps_init_tool.sh' 'confirm_phrase .*"RESET"' 'vps_init_tool.sh UFW reset must use explicit phrase confirmation'
Check-Contains 'vps_init_tool.sh' 'if \[ "\$#" -gt 0 \]; then' 'vps_init_tool.sh interactive startup must not call the empty CLI dispatcher'
Check-Contains 'vps_init_tool.sh' 'VPS_INIT_LIB_ONLY' 'vps_init_tool.sh must expose a non-executing library mode for UI regression tests'
Check-Contains 'vps_init_tool.sh' 'Missing value for --ports' 'vps_init_tool.sh CLI must report a missing --ports value'
Check-Contains 'vps_init_tool.sh' 'Only one command may be specified' 'vps_init_tool.sh CLI must reject multiple commands'
Check-Contains 'vps_init_tool.sh' 'original_args="\$[*]"' 'vps_init_tool.sh CLI logging must preserve original arguments before shifting'
Check-Contains 'vps_init_tool.sh' 'log_action "cli" "command=\$cmd args=\$original_args"' 'vps_init_tool.sh CLI log must use preserved original arguments'
Check-Contains 'vps_init_tool.sh' 'local cmd="" original_args="\$[*]" rc=0' 'vps_init_tool.sh CLI must track command return code'
Check-Contains 'vps_init_tool.sh' 'set \+e' 'vps_init_tool.sh CLI must disable errexit while capturing command rc'
Check-Contains 'vps_init_tool.sh' '\(\s+set -e\s+case "\$cmd" in' 'vps_init_tool.sh CLI commands must run in an errexit-enabled subshell'
Check-Contains 'vps_init_tool.sh' 'log_action "cli" "command=\$cmd complete rc=\$rc"' 'vps_init_tool.sh CLI completion log must include rc'
Check-Contains 'vps_init_tool.sh' 'exit "\$rc"' 'vps_init_tool.sh CLI must exit with captured rc'
Check-NotExactLine 'vps_init_tool.sh' '  log_action "cli" "command=$cmd complete"' 'vps_init_tool.sh CLI completion log must not omit rc'
Check-Contains 'vps_init_tool.sh' 'LOG_FILE=' 'vps_init_tool.sh missing operation log file setting'
Check-Contains 'vps_init_tool.sh' 'log_action\(\)' 'vps_init_tool.sh missing operation logger'
Check-Contains 'vps_init_tool.sh' 'restore_managed_file\(\)' 'vps_init_tool.sh missing managed configuration rollback helper'
Check-Contains 'vps_init_tool.sh' 'require_systemd\(\)' 'vps_init_tool.sh missing systemd requirement helper'
Check-Contains 'vps_init_tool.sh' 'systemd is required for this module' 'vps_init_tool.sh systemd helper must explain unsupported service modules'
Check-NotContains 'vps_init_tool.sh' 'is_systemd \|\| \{ red "\$\(m ''systemd not detected\.''' 'vps_init_tool.sh service modules must use require_systemd helper'
Check-Contains 'vps_init_tool.sh' 'normalize_yes_no\(\)' 'vps_init_tool.sh missing y/n normalization helper'
Check-Contains 'vps_init_tool.sh' 'input_yes_no\(\)' 'vps_init_tool.sh missing y/n compatible yes/no prompt helper'
Check-Contains 'vps_init_tool.sh' 'normalize_password_policy\(\)' 'vps_init_tool.sh missing y/n compatible SSH password policy helper'
Check-Contains 'vps_init_tool.sh' 'valid_permit_root_login\(\)' 'vps_init_tool.sh missing PermitRootLogin validator'
Check-Contains 'vps_init_tool.sh' 'yes\|prohibit-password\|without-password\|forced-commands-only\|no' 'vps_init_tool.sh PermitRootLogin validator must allow only OpenSSH policies'
Check-Contains 'vps_init_tool.sh' 'valid_permit_root_login "\$permit_root" \|\| \{ red "\$\(m ''Invalid PermitRootLogin policy\. Use yes, prohibit-password, forced-commands-only, no, or without-password\.''' 'vps_init_tool.sh must validate PermitRootLogin before writing SSH hardening'
Check-Contains 'vps_init_tool.sh' 'valid_allow_users_value\(\)' 'vps_init_tool.sh missing AllowUsers validator'
Check-Contains 'vps_init_tool.sh' 'valid_allow_users_value "\$allow_user".*Invalid AllowUsers value' 'vps_init_tool.sh must validate AllowUsers before writing SSH hardening'
Check-Contains 'vps_init_tool.sh' 'ssh_effective_value_from_text\(\)' 'vps_init_tool.sh missing effective sshd value parser'
Check-Contains 'vps_init_tool.sh' 'ssh_verify_hardening_effective\(\)' 'vps_init_tool.sh missing effective SSH hardening verification'
Check-Contains 'vps_init_tool.sh' 'fragment_tmp="\$\(mktemp "/etc/ssh/sshd_config\.d/\.00-vps-init-hardening\.conf\.XXXXXX"\)"' 'vps_init_tool.sh must stage SSH hardening in the target directory'
Check-Contains 'vps_init_tool.sh' 'mv -f -- "\$fragment_tmp" "\$SSH_HARDENING_FRAGMENT"' 'vps_init_tool.sh must atomically replace the SSH hardening fragment'
Check-NotContains 'vps_init_tool.sh' 'cat > "\$SSH_HARDENING_FRAGMENT"' 'vps_init_tool.sh must not truncate the live SSH hardening fragment directly'
Check-Contains 'vps_init_tool.sh' 'ssh_verify_hardening_effective "\$port" "\$password_policy" "\$permit_root" "\$strict_forwarding" "\$allow_tcp" "\$allow_user"' 'vps_init_tool.sh must verify effective SSH settings after staging the fragment'
Check-Contains 'vps_init_tool.sh' 'SSH hardening did not become effective\. Restoring the previous fragment\.' 'vps_init_tool.sh must explain effective SSH verification rollback'
Check-Contains 'vps_init_tool.sh' 'APT_LOCK_TIMEOUT=' 'vps_init_tool.sh missing apt lock timeout setting'
Check-Contains 'vps_init_tool.sh' 'APT_RETRIES=' 'vps_init_tool.sh missing apt retry setting'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry\(\)' 'vps_init_tool.sh missing apt retry helper'
Check-Contains 'vps_init_tool.sh' 'DPkg::Lock::Timeout=' 'vps_init_tool.sh apt operations must wait for dpkg locks'
Check-Contains 'vps_init_tool.sh' 'errexit_was_set=0' 'vps_init_tool.sh apt retry must preserve errexit state'
Check-Contains 'vps_init_tool.sh' 'case "\$-" in' 'vps_init_tool.sh apt retry must inspect shell option state'
Check-Contains 'vps_init_tool.sh' '\*e\*\) errexit_was_set=1' 'vps_init_tool.sh apt retry must detect errexit'
Check-Contains 'vps_init_tool.sh' '\[ "\$errexit_was_set" -eq 1 \] && set -e' 'vps_init_tool.sh apt retry must restore errexit'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry update' 'vps_init_tool.sh apt update must use retry helper'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry install -y "\$@"' 'vps_init_tool.sh apt install must use retry helper'
Check-Contains 'vps_init_tool.sh' 'apt_get_retry update \|\| return 1' 'vps_init_tool.sh apt update failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'apt_update_once \|\| return 1' 'vps_init_tool.sh apt install must stop when apt update fails'
Check-NotContains 'vps_init_tool.sh' 'systemctl enable cron >/dev/null 2>&1 \|\| true' 'vps_init_tool.sh must not silently hide cron enable failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl enable sysstat >/dev/null 2>&1 \|\| true' 'vps_init_tool.sh must not silently hide sysstat enable failures'
Check-Contains 'vps_init_tool.sh' 'Failed to enable cron service' 'vps_init_tool.sh should warn if cron enable fails'
Check-Contains 'vps_init_tool.sh' 'Failed to enable sysstat service' 'vps_init_tool.sh should warn if sysstat enable fails'
Check-Contains 'vps_init_tool.sh' 'if \[ "\$max_by_disk_mb" -lt 512 \]; then echo "0M"; return 0; fi' 'vps_init_tool.sh must skip swapfile recommendation when disk space is too low'
Check-Contains 'vps_init_tool.sh' 'valid_size_mb_gb\(\)' 'vps_init_tool.sh missing size validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_uint_range\(\)' 'vps_init_tool.sh missing numeric range validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_ip_or_cidr\(\)' 'vps_init_tool.sh missing IP/CIDR validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_ipv4_literal "\$addr" && valid_uint_range "\$prefix" 0 32' 'vps_init_tool.sh IPv4 CIDR validator must enforce /0-/32'
Check-Contains 'vps_init_tool.sh' 'valid_ipv6_literal "\$addr" && valid_uint_range "\$prefix" 0 128' 'vps_init_tool.sh IPv6 CIDR validator must enforce /0-/128'
Check-Contains 'vps_init_tool.sh' 'Invalid swapfile size' 'vps_init_tool.sh must reject invalid swapfile sizes'
Check-Contains 'vps_init_tool.sh' 'cleanup_failed_swapfile_creation\(\)' 'vps_init_tool.sh missing swapfile creation cleanup helper'
Check-Contains 'vps_init_tool.sh' 'restore_previous_swapfile\(\)' 'vps_init_tool.sh missing previous swapfile restore helper'
Check-Contains 'vps_init_tool.sh' 'rollback_new_swapfile\(\)' 'vps_init_tool.sh missing new swapfile rollback helper'
Check-Contains 'vps_init_tool.sh' 'old_swap_backup=' 'vps_init_tool.sh must preserve an existing swapfile while replacing it'
Check-Contains 'vps_init_tool.sh' 'new_swap_tmp=' 'vps_init_tool.sh must prepare a new swapfile before replacing the old one'
Check-Contains 'vps_init_tool.sh' 'fstab_backup=' 'vps_init_tool.sh must track fstab backup while persisting swapfile'
Check-Contains 'vps_init_tool.sh' 'new_swap_tmp="\$\(mktemp "\$\{SWAPFILE\}\.new\.XXXXXX"\)" \|\| return 1' 'vps_init_tool.sh must use mktemp for new swapfile staging path'
Check-Contains 'vps_init_tool.sh' 'old_swap_backup="\$\(mktemp "\$\{SWAPFILE\}\.old\.XXXXXX"\)"' 'vps_init_tool.sh must use mktemp for previous swapfile backup path'
Check-Contains 'vps_init_tool.sh' 'cleanup_files "\$old_swap_backup" "\$new_swap_tmp"' 'vps_init_tool.sh must cleanup reserved old swap backup path if swapoff fails'
Check-Contains 'vps_init_tool.sh' 'cleanup_files "\$old_swap_backup"' 'vps_init_tool.sh must cleanup reserved old swap backup path if preserving previous swapfile fails'
Check-NotContains 'vps_init_tool.sh' 'new_swap_tmp="\$\{SWAPFILE\}\.new\.\$\$"' 'vps_init_tool.sh must not use predictable pid-based new swapfile path'
Check-NotContains 'vps_init_tool.sh' 'old_swap_backup="\$\{SWAPFILE\}\.old\.\$\$"' 'vps_init_tool.sh must not use predictable pid-based old swapfile path'
Check-Contains 'vps_init_tool.sh' 'mv "\$SWAPFILE" "\$old_swap_backup"' 'vps_init_tool.sh must rename the previous swapfile before replacement'
Check-Contains 'vps_init_tool.sh' 'restore_previous_swapfile "\$old_swap_backup" "\$swap_was_active"' 'vps_init_tool.sh must restore the previous swapfile if replacement fails'
Check-Contains 'vps_init_tool.sh' 'restore_managed_file /etc/fstab "\$fstab_backup"' 'vps_init_tool.sh must restore fstab if swap persistence fails'
Check-Contains 'vps_init_tool.sh' 'rollback_new_swapfile "\$old_swap_backup" "\$swap_was_active"' 'vps_init_tool.sh must rollback the new swapfile if persistence fails'
Check-Contains 'vps_init_tool.sh' 'Failed to update /etc/fstab. Restoring previous swapfile.' 'vps_init_tool.sh must report fstab persistence failure'
Check-Contains 'vps_init_tool.sh' 'Swapfile is active, but VM sysctl tuning failed.' 'vps_init_tool.sh must clearly report post-swap sysctl failures'
Check-Contains 'vps_init_tool.sh' 'if ! apply_memory_sysctl "\$swappiness" "\$vfs_cache_pressure"; then' 'vps_init_tool.sh must handle post-swap sysctl failures explicitly'
Check-Contains 'vps_init_tool.sh' 'Failed to create swapfile data. Cleaning up partial file.' 'vps_init_tool.sh must cleanup partial swapfile data after dd failure'
Check-Contains 'vps_init_tool.sh' 'Failed to activate swapfile. Cleaning up partial file.' 'vps_init_tool.sh must cleanup partial swapfile after swapon failure'
Check-Contains 'vps_init_tool.sh' 'if ! dd if=/dev/zero of="\$new_swap_tmp" bs=1M count="\$mb" status=progress; then' 'vps_init_tool.sh must handle swapfile dd failures explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! chmod 600 "\$new_swap_tmp"; then' 'vps_init_tool.sh must handle swapfile chmod failures explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! mkswap "\$new_swap_tmp"; then' 'vps_init_tool.sh must handle mkswap failures explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! swapon -p 10 "\$SWAPFILE"; then' 'vps_init_tool.sh must handle swapon failures explicitly'
Check-Contains 'vps_init_tool.sh' 'sysctl -p /etc/sysctl\.d/99-memory-tuning\.conf' 'vps_init_tool.sh must apply and validate its memory sysctl file directly'
Check-Contains 'vps_init_tool.sh' 'sysctl -p /etc/sysctl\.d/90-bbr\.conf' 'vps_init_tool.sh must apply and validate its BBR sysctl file directly'
Check-Contains 'vps_init_tool.sh' 'sysctl -p /etc/sysctl\.d/99-proxy-tuning\.conf' 'vps_init_tool.sh must apply and validate its proxy sysctl file directly'
Check-Contains 'vps_init_tool.sh' 'if ! sysctl -p /etc/sysctl\.d/99-memory-tuning\.conf >/dev/null; then' 'vps_init_tool.sh memory sysctl failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! sysctl -p /etc/sysctl\.d/90-bbr\.conf >/dev/null; then' 'vps_init_tool.sh BBR sysctl failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'if ! sysctl -p /etc/sysctl\.d/99-proxy-tuning\.conf >/dev/null; then' 'vps_init_tool.sh proxy sysctl failures must propagate explicitly'
Check-Contains 'vps_init_tool.sh' 'restore_managed_file "\$config_file" "\$config_backup"' 'vps_init_tool.sh persistent configuration failures must restore the previous file'
Check-Contains 'vps_init_tool.sh' 'restore_sysctl_file\(\)' 'vps_init_tool.sh missing sysctl rollback apply helper'
Check-Contains 'vps_init_tool.sh' 'Failed to re-apply restored sysctl file' 'vps_init_tool.sh must warn if restored sysctl config cannot be applied'
Check-NotContains 'vps_init_tool.sh' 'sysctl -p "\$config_file" >/dev/null 2>&1 \|\| true' 'vps_init_tool.sh must not silently hide restored sysctl apply failures'
Check-NotContains 'vps_init_tool.sh' 'sysctl --system >/dev/null \|\| true' 'vps_init_tool.sh must not hide sysctl application failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart systemd-zram-setup@zram0\.service 2>/dev/null \|\| systemctl start systemd-zram-setup@zram0\.service 2>/dev/null \|\| true' 'vps_init_tool.sh must not hide zram-generator activation failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart zramswap\.service 2>/dev/null \|\| systemctl restart zram-config\.service 2>/dev/null \|\| true' 'vps_init_tool.sh must not hide zram-tools activation failures'
Check-Contains 'vps_init_tool.sh' 'ZRAM generator activation failed\. Restoring the previous configuration\.' 'vps_init_tool.sh must report zram-generator rollback'
Check-Contains 'vps_init_tool.sh' 'ZRAM tools activation failed\. Restoring the previous configuration\.' 'vps_init_tool.sh must report zram-tools rollback'
Check-Contains 'vps_init_tool.sh' 'restore_managed_file "\$config_file" "\$config_backup"' 'vps_init_tool.sh ZRAM backends must restore previous managed configuration on failure'
Check-NotContains 'vps_init_tool.sh' 'setup_zram_generator \|\| \{ stop_known_zram_services; setup_zram_fallback; \}' 'vps_init_tool.sh must not layer fallback ZRAM over a failed generator backend'
Check-NotContains 'vps_init_tool.sh' 'setup_zram_tools "\$size_hint" \|\| \{ stop_known_zram_services; setup_zram_fallback; \}' 'vps_init_tool.sh must not layer fallback ZRAM over failed zram-tools'
Check-Contains 'vps_init_tool.sh' 'setup_zram_generator "\$zram_was_active" \|\| return 1' 'vps_init_tool.sh must propagate zram-generator activation failure'
Check-Contains 'vps_init_tool.sh' 'setup_zram_tools "\$size_hint" \|\| return 1' 'vps_init_tool.sh must propagate zram-tools activation failure'
Check-Contains 'vps_init_tool.sh' 'normalize_zram_generator_size\(\)' 'vps_init_tool.sh must normalize zram-generator size syntax'
Check-NotContains 'vps_init_tool.sh' 'min\(ram / 2, 1024M\)' 'vps_init_tool.sh must not suggest SI suffixes inside zram-generator expressions'
Check-Contains 'vps_init_tool.sh' '--baseline' 'vps_init_tool.sh missing low-risk baseline CLI'
Check-Contains 'vps_init_tool.sh' '--preflight' 'vps_init_tool.sh missing read-only preflight CLI'
Check-Contains 'vps_init_tool.sh' 'preflight_check\(\)' 'vps_init_tool.sh missing read-only preflight helper'
Check-Contains 'vps_init_tool.sh' '--preflight\) preflight_check; exit 0 ;;' 'vps_init_tool.sh preflight must run before root-only CLI gates'
Check-Contains 'vps_init_tool.sh' 'low_risk_baseline "cli"' 'vps_init_tool.sh CLI baseline must use explicit cli mode'
Check-NotExactLine 'vps_init_tool.sh' '  setup_swapfile || true' 'vps_init_tool.sh low-risk baseline must not recreate swapfile automatically'
Check-NotExactLine 'vps_init_tool.sh' '  setup_zram || true' 'vps_init_tool.sh low-risk baseline must not reconfigure ZRAM automatically'
Check-NotExactLine 'vps_init_tool.sh' '  if ! apply_proxy_sysctl; then failures=$((failures + 1)); fi' 'vps_init_tool.sh low-risk baseline must not apply global proxy sysctl tuning'
Check-NotExactLine 'vps_init_tool.sh' '  if ! raise_nofile_limits; then failures=$((failures + 1)); fi' 'vps_init_tool.sh low-risk baseline must not raise global nofile limits'
Check-Contains 'vps_init_tool.sh' 'Advanced proxy sysctl tuning changes global TCP behavior' 'vps_init_tool.sh advanced proxy sysctl tuning must warn before applying'
Check-Contains 'vps_init_tool.sh' 'Apply advanced global proxy sysctl tuning\?' 'vps_init_tool.sh advanced proxy sysctl tuning must require confirmation'
Check-Contains 'vps_init_tool.sh' 'Global nofile tuning affects all users and default systemd service limits' 'vps_init_tool.sh global nofile tuning must warn before applying'
Check-Contains 'vps_init_tool.sh' 'Raise global nofile defaults\?' 'vps_init_tool.sh global nofile tuning must require confirmation'
Check-Contains 'vps_init_tool.sh' 'Baseline completed with' 'vps_init_tool.sh baseline must report partial failures'
Check-Contains 'vps_init_tool.sh' 'return 1' 'vps_init_tool.sh baseline must be able to return failure'
Check-Contains 'vps_init_tool.sh' '--ufw-cf-sync' 'vps_init_tool.sh missing Cloudflare UFW sync CLI'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_STATE_FILE=' 'vps_init_tool.sh missing Cloudflare UFW state file'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_LOCK_FILE=' 'vps_init_tool.sh missing Cloudflare UFW lock file'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_LOCK_TIMEOUT=' 'vps_init_tool.sh missing Cloudflare UFW lock timeout'
Check-Contains 'vps_init_tool.sh' 'UFW_CF_LOCK_FD=""' 'vps_init_tool.sh Cloudflare UFW lock fd must be held globally'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_acquire\(\)' 'vps_init_tool.sh missing Cloudflare UFW lock helper'
Check-Contains 'vps_init_tool.sh' 'flock is required for safe Cloudflare UFW sync' 'vps_init_tool.sh must fail safely when flock is unavailable'
Check-Contains 'vps_init_tool.sh' 'exec \{UFW_CF_LOCK_FD\}>"\$UFW_CF_LOCK_FILE"' 'vps_init_tool.sh Cloudflare UFW lock must use a dynamic fd held globally'
Check-Contains 'vps_init_tool.sh' 'flock -w "\${UFW_CF_LOCK_TIMEOUT:-120}" "\$UFW_CF_LOCK_FD"' 'vps_init_tool.sh Cloudflare UFW sync must use flock with timeout'
Check-Contains 'vps_init_tool.sh' 'exec \{UFW_CF_LOCK_FD\}>&- 2>/dev/null \|\| true' 'vps_init_tool.sh must close Cloudflare UFW lock fd if flock acquisition fails'
Check-NotContains 'vps_init_tool.sh' 'exec 9>"\$UFW_CF_LOCK_FILE"' 'vps_init_tool.sh Cloudflare UFW lock must not reserve fixed fd 9'
Check-NotContains 'vps_init_tool.sh' 'local lock_fd' 'vps_init_tool.sh Cloudflare UFW lock fd must not be local to acquire helper'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_release\(\)' 'vps_init_tool.sh missing Cloudflare UFW lock release helper'
Check-Contains 'vps_init_tool.sh' 'flock -u "\$UFW_CF_LOCK_FD"' 'vps_init_tool.sh Cloudflare UFW lock release must unlock fd'
Check-Contains 'vps_init_tool.sh' 'exec \{UFW_CF_LOCK_FD\}>&-' 'vps_init_tool.sh Cloudflare UFW lock release must close fd'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_release' 'vps_init_tool.sh Cloudflare UFW sync must release lock explicitly'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_lock_acquire || return 1' 'vps_init_tool.sh Cloudflare UFW sync must acquire lock before mutating rules'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_sync_cleanup\(\)' 'vps_init_tool.sh missing Cloudflare UFW sync RETURN cleanup helper'
Check-Contains 'vps_init_tool.sh' 'cleanup_files "\$@"' 'vps_init_tool.sh Cloudflare UFW cleanup helper must use explicit path arguments'
Check-Contains 'vps_init_tool.sh' 'local ports desired="" current="" adds="" deletes=""' 'vps_init_tool.sh Cloudflare UFW temp paths must initialize empty before cleanup'
Check-Contains 'vps_init_tool.sh' 'ufw_ensure_ssh_access \|\| \{ ufw_cf_sync_cleanup "\$desired"' 'vps_init_tool.sh must cleanup Cloudflare UFW sync if SSH allow check fails'
Check-Contains 'vps_init_tool.sh' 'cf_fetch_ranges \|\| \{ ufw_cf_sync_cleanup "\$desired"' 'vps_init_tool.sh must cleanup Cloudflare UFW sync if Cloudflare ranges fetch fails'
Check-Contains 'vps_init_tool.sh' 'desired="\$\(mktemp\)" \|\| \{ ufw_cf_sync_cleanup "\$desired"' 'vps_init_tool.sh Cloudflare UFW sync must cleanup if desired temp creation fails'
Check-Contains 'vps_init_tool.sh' 'cleanup_files\(\)' 'vps_init_tool.sh missing temp-file cleanup helper'
Check-Contains 'vps_init_tool.sh' 'rm -f -- "\$@"' 'vps_init_tool.sh cleanup helper must use rm -- for path safety'
Check-Contains 'vps_init_tool.sh' 'v4_tmp="\$\(mktemp "\$\(dirname "\$UFW_CF_IPV4_FILE"\)/cloudflare-ips-v4\.txt\.XXXXXX"\)" \|\| return 1' 'vps_init_tool.sh Cloudflare v4 temp creation must fail safely'
Check-Contains 'vps_init_tool.sh' 'v6_tmp="\$\(mktemp "\$\(dirname "\$UFW_CF_IPV6_FILE"\)/cloudflare-ips-v6\.txt\.XXXXXX"\)" \|\| \{ cleanup_files "\$v4_tmp"; return 1; \}' 'vps_init_tool.sh Cloudflare v6 temp creation must cleanup v4 temp on failure'
Check-Contains 'vps_init_tool.sh' 'cleanup_files "\$v4_tmp" "\$v6_tmp"' 'vps_init_tool.sh Cloudflare range fetch must cleanup temp downloads on failure'
Check-Contains 'vps_init_tool.sh' 'if ! mv "\$v4_tmp" "\$UFW_CF_IPV4_FILE"; then cleanup_files "\$v4_tmp" "\$v6_tmp"; return 1; fi' 'vps_init_tool.sh must cleanup temp Cloudflare v4 file if mv fails'
Check-Contains 'vps_init_tool.sh' 'if ! mv "\$v6_tmp" "\$UFW_CF_IPV6_FILE"; then cleanup_files "\$v4_tmp" "\$v6_tmp"; return 1; fi' 'vps_init_tool.sh must cleanup temp Cloudflare v6 file if mv fails'
Check-Contains 'vps_init_tool.sh' 'validate_cloudflare_range_file\(\)' 'vps_init_tool.sh must validate every downloaded Cloudflare range'
Check-Contains 'vps_init_tool.sh' 'Cloudflare IPv\$\{family\} entry is not a CIDR' 'vps_init_tool.sh must reject non-CIDR Cloudflare entries'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_state_commit\(\)' 'vps_init_tool.sh missing atomic Cloudflare managed-state writer'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_state_add "\$current" "\$cidr" "\$p"' 'vps_init_tool.sh must persist successful Cloudflare additions immediately'
Check-Contains 'vps_init_tool.sh' 'ufw_cf_state_remove "\$current" "\$cidr" "\$p"' 'vps_init_tool.sh must persist successful Cloudflare deletions immediately'
Check-Contains 'vps_init_tool.sh' 'rm -f -- "\$UFW_CF_STATE_FILE"' 'vps_init_tool.sh UFW reset must clear managed Cloudflare state'
Check-NotContains 'vps_init_tool.sh' 'ufw allow proto tcp from "\$cidr" to any port "\$p" comment "cloudflare-\$p" \|\| true' 'vps_init_tool.sh must not record failed Cloudflare UFW additions as synced'
Check-NotContains 'vps_init_tool.sh' 'ufw --force delete allow proto tcp from "\$cidr" to any port "\$port" >/dev/null 2>&1 \|\| true' 'vps_init_tool.sh must not record failed Cloudflare UFW deletions as synced'
Check-Contains 'vps_init_tool.sh' 'ufw --force delete allow proto tcp from "\$cidr" to any port "\$port" comment "cloudflare-\$port"' 'vps_init_tool.sh must delete only Cloudflare UFW rules marked by this tool'
Check-Contains 'vps_init_tool.sh' 'Cloudflare UFW add failed' 'vps_init_tool.sh must report failed Cloudflare UFW additions'
Check-Contains 'vps_init_tool.sh' 'Cloudflare UFW delete failed' 'vps_init_tool.sh must report failed Cloudflare UFW deletions'
Check-Contains 'vps_init_tool.sh' 'ssh_reload_or_restart\(\)' 'vps_init_tool.sh missing SSH reload/restart helper'
Check-Contains 'vps_init_tool.sh' 'ssh_remove_hardening_fragment\(\)' 'vps_init_tool.sh missing SSH hardening rollback helper'
Check-Contains 'vps_init_tool.sh' 'ssh_restore_hardening_backup\(\)' 'vps_init_tool.sh missing SSH hardening backup restore helper'
Check-Contains 'vps_init_tool.sh' 'fragment_backup="\$BACKUP_LAST_PATH"' 'vps_init_tool.sh must retain the previous SSH hardening fragment backup path'
Check-Contains 'vps_init_tool.sh' 'ssh_restore_hardening_backup "\$fragment_backup"' 'vps_init_tool.sh must restore the previous SSH hardening fragment on failure'
Check-Contains 'vps_init_tool.sh' 'ssh_key_line_valid\(\)' 'vps_init_tool.sh missing authorized_keys line validator'
Check-Contains 'vps_init_tool.sh' 'ssh_path_secure_for_user\(\)' 'vps_init_tool.sh missing SSH key-path permission validator'
Check-Contains 'vps_init_tool.sh' '8#022' 'vps_init_tool.sh must reject group/world-writable SSH key paths'
Check-Contains 'vps_init_tool.sh' 'user_has_authorized_key\(\)' 'vps_init_tool.sh missing key-login readiness helper'
Check-Contains 'vps_init_tool.sh' 'ssh_require_key_login_ready\(\)' 'vps_init_tool.sh must verify usable public keys before disabling SSH passwords'
Check-Contains 'vps_init_tool.sh' '\[ "\$password_policy" = "no" \] \|\| \[ "\$permit_root" != "yes" \]' 'vps_init_tool.sh must verify key access when restricting root or password login'
Check-Contains 'vps_init_tool.sh' 'valid_ssh_public_key\(\)' 'vps_init_tool.sh missing SSH public key format validation helper'
Check-Contains 'vps_init_tool.sh' 'ssh-keygen -l -f' 'vps_init_tool.sh must validate SSH public keys with ssh-keygen when available'
Check-Contains 'vps_init_tool.sh' 'valid_ssh_public_key "\$key"' 'vps_init_tool.sh must validate SSH public keys before installing'
Check-Contains 'vps_init_tool.sh' 'group="\$\(id -gn "\$user" 2>/dev/null \|\| echo "\$user"\)"' 'vps_init_tool.sh must chown SSH keys using the user primary group'
Check-Contains 'vps_init_tool.sh' 'SSH_CONNECTION' 'vps_init_tool.sh must include the current SSH session port when protecting firewall access'
Check-Contains 'vps_init_tool.sh' 'ufw_ensure_ssh_access \|\| \{ ssh_restore_hardening_backup "\$fragment_backup"; return 1; \}' 'vps_init_tool.sh SSH hardening must protect current SSH ports before reload'
Check-Contains 'vps_init_tool.sh' 'SSH firewall allow failed' 'vps_init_tool.sh must abort SSH hardening if the firewall rule cannot be added'
Check-NotContains 'vps_init_tool.sh' 'if has_cmd ufw; then ufw allow "\$port/tcp" comment "SSH" \|\| true; fi' 'vps_init_tool.sh must not ignore SSH firewall allow failures'
Check-Contains 'vps_init_tool.sh' 'SSH service reload/restart failed' 'vps_init_tool.sh must report failed SSH activation'
Check-NotContains 'vps_init_tool.sh' 'PasswordAuthentication yes' 'vps_init_tool.sh must not force SSH password login on'
Check-NotContains 'vps_init_tool.sh' 'systemctl reload ssh 2>/dev/null \|\| systemctl reload sshd 2>/dev/null \|\| systemctl restart ssh 2>/dev/null \|\| systemctl restart sshd 2>/dev/null \|\| true' 'vps_init_tool.sh must not silently ignore SSH reload/restart failures'
Check-Contains 'vps_init_tool.sh' 'fail2ban-client -t' 'vps_init_tool.sh must validate Fail2ban configuration before activation'
Check-Contains 'vps_init_tool.sh' 'Fail2ban configuration test failed' 'vps_init_tool.sh must report invalid Fail2ban configuration'
Check-Contains 'vps_init_tool.sh' 'ufw status 2>/dev/null \| grep -q ''\^Status: active''' 'vps_init_tool.sh must use the UFW Fail2ban action only when UFW is active'
Check-Contains 'vps_init_tool.sh' 'valid_ip_literal\(\)' 'vps_init_tool.sh missing IP literal validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_ip_list\(\)' 'vps_init_tool.sh missing DNS server list validation helper'
Check-Contains 'vps_init_tool.sh' 'Invalid primary DNS server list' 'vps_init_tool.sh must reject invalid systemd-resolved DNS server lists'
Check-Contains 'vps_init_tool.sh' 'valid_ip_or_cidr "\$ip".*Invalid source IP/CIDR' 'vps_init_tool.sh UFW source allow must accept and validate CIDR sources'
Check-Contains 'vps_init_tool.sh' '\[ -L /etc/resolv\.conf \]' 'vps_init_tool.sh must not directly overwrite a managed resolv.conf symlink'
Check-Contains 'vps_init_tool.sh' 'dns_restore_resolved_backup\(\)' 'vps_init_tool.sh missing systemd-resolved rollback helper'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart systemd-resolved 2>/dev/null \|\| true' 'vps_init_tool.sh must not silently hide DNS rollback restart failures'
Check-Contains 'vps_init_tool.sh' 'Failed to restart systemd-resolved after restoring backup' 'vps_init_tool.sh must warn if DNS rollback restart fails'
Check-NotContains 'vps_init_tool.sh' 'DNSSEC=no' 'vps_init_tool.sh must not force DNSSEC off'
Check-Contains 'vps_init_tool.sh' 'valid_systemd_size\(\)' 'vps_init_tool.sh missing journald size validation helper'
Check-Contains 'vps_init_tool.sh' 'valid_systemd_timespan\(\)' 'vps_init_tool.sh missing journald retention validation helper'
Check-Contains 'vps_init_tool.sh' 'apt_config_value_from_text\(\)' 'vps_init_tool.sh missing APT configuration value parser'
Check-Contains 'vps_init_tool.sh' 'security_updates_audit\(\)' 'vps_init_tool.sh missing automatic security updates audit'
Check-Contains 'vps_init_tool.sh' 'security_updates_write_policy\(\)' 'vps_init_tool.sh missing transactional automatic updates policy writer'
Check-Contains 'vps_init_tool.sh' 'security_updates_policy_effective\(\)' 'vps_init_tool.sh missing effective automatic updates policy verification'
Check-Contains 'vps_init_tool.sh' 'security_updates_enable\(\)' 'vps_init_tool.sh missing automatic security updates enable function'
Check-Contains 'vps_init_tool.sh' 'security_updates_disable\(\)' 'vps_init_tool.sh missing automatic security updates disable function'
Check-Contains 'vps_init_tool.sh' 'Unattended-Upgrade::Automatic-Reboot "false";' 'vps_init_tool.sh automatic security updates must not reboot by default'
Check-Contains 'vps_init_tool.sh' 'APT::Periodic::Update-Package-Lists "\$enabled";' 'vps_init_tool.sh automatic updates policy must control package-list refresh'
Check-Contains 'vps_init_tool.sh' 'APT::Periodic::Unattended-Upgrade "\$enabled";' 'vps_init_tool.sh automatic updates policy must control unattended upgrades'
Check-NotContains 'vps_init_tool.sh' 'Unattended-Upgrade::Allowed-Origins|Unattended-Upgrade::Origins-Pattern' 'vps_init_tool.sh must preserve distro-provided security origin policy'
Check-Contains 'vps_init_tool.sh' 'policy_dir="\$\(dirname "\$AUTO_UPGRADES_CONFIG"\)"' 'vps_init_tool.sh automatic updates policy must derive its managed directory'
Check-Contains 'vps_init_tool.sh' 'policy_tmp="\$\(mktemp "\$policy_dir/\.52-vps-init-auto-upgrades\.XXXXXX"\)"' 'vps_init_tool.sh must stage automatic updates policy atomically'
Check-Contains 'vps_init_tool.sh' 'mv -f -- "\$policy_tmp" "\$AUTO_UPGRADES_CONFIG"' 'vps_init_tool.sh must atomically install automatic updates policy'
Check-Contains 'vps_init_tool.sh' 'apt-config dump >/dev/null' 'vps_init_tool.sh must validate APT configuration after policy changes'
Check-Contains 'vps_init_tool.sh' 'security_updates_policy_effective "\$enabled"' 'vps_init_tool.sh must verify automatic updates settings are effective after writing'
Check-Contains 'vps_init_tool.sh' 'systemctl enable --now apt-daily\.timer apt-daily-upgrade\.timer' 'vps_init_tool.sh must enable standard APT timers'
Check-NotExactLine 'vps_init_tool.sh' '  security_updates_enable || true' 'vps_init_tool.sh low-risk baseline must not silently enable automatic security updates'
Check-Contains 'vps_init_tool.sh' 'It does NOT change SSH, UFW, DNS, Fail2ban, automatic security updates, global proxy sysctl/nofile tuning, swapfile, or ZRAM\.' 'vps_init_tool.sh baseline must clearly exclude high-impact modules'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart systemd-journald \|\| true' 'vps_init_tool.sh must not hide journald restart failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart systemd-journald 2>/dev/null \|\| true' 'vps_init_tool.sh must not silently hide journald rollback restart failures'
Check-Contains 'vps_init_tool.sh' 'Failed to restart systemd-journald after restoring backup' 'vps_init_tool.sh must warn if journald rollback restart fails'
Check-NotContains 'vps_init_tool.sh' 'backup_path .* >/dev/null \|\| true' 'vps_init_tool.sh must not overwrite managed configuration after a failed backup'
Check-NotContains 'vps_init_tool.sh' 'ufw limit "\$p/tcp" comment "rate-limit-ssh" \|\| true' 'vps_init_tool.sh must not hide SSH rate-limit rule failures'
Check-NotContains 'vps_init_tool.sh' 'fail2ban-client set "\$jail" unbanip "\$ip" \|\| true' 'vps_init_tool.sh must not hide Fail2ban unban failures'
Check-NotContains 'vps_init_tool.sh' 'systemctl restart fail2ban 2>/dev/null \|\| true' 'vps_init_tool.sh must not silently hide Fail2ban rollback restart failures'
Check-Contains 'vps_init_tool.sh' 'Failed to restart fail2ban after restoring jail' 'vps_init_tool.sh must warn if Fail2ban rollback restart fails'
Check-Contains 'vps_init_tool.sh' 'Swapfile size verification failed' 'vps_init_tool.sh must verify swapfile allocation size'
Check-Contains 'vps_init_tool.sh' 'valid_ip_literal "\$ip"' 'vps_init_tool.sh must validate Fail2ban unban IP addresses'
Check-Contains 'vps_init_tool.sh' 'Invalid IP to unban' 'vps_init_tool.sh must report invalid Fail2ban unban IP addresses'

Check-Contains 'freedom.sh' 'SCRIPT_VERSION="v10\.2-xray"' 'freedom.sh version drifted'
Check-Contains 'freedom.sh' 'DEFAULT_SNI="v1-dy\.ixigua\.com"' 'freedom.sh default SNI drifted'
Check-Contains 'freedom.sh' 'ipv6_is_non_global\(\)' 'freedom.sh missing precise non-global IPv6 classifier'
Check-Contains 'freedom.sh' 'first_value >= 16#fe80 && first_value <= 16#febf' 'freedom.sh must cover the complete IPv6 link-local fe80::/10 range'
Check-Contains 'freedom.sh' 'first_value >= 16#fc00 && first_value <= 16#fdff' 'freedom.sh must cover IPv6 ULA fc00::/7 precisely'
Check-NotContains 'freedom.sh' 'fe80:\*\|fc\*\|fd\*' 'freedom.sh must not use overbroad IPv6 prefix globs'
Check-Contains 'freedom.sh' 'ensure_xray_installed\(\)' 'freedom.sh must install/configure Xray-core only'
Check-Contains 'freedom.sh' 'ensure_xray_capabilities\(\)' 'freedom.sh must validate selected-profile Xray capabilities before deployment'
Check-Contains 'freedom.sh' 'missing_xray_capabilities\(\)' 'freedom.sh missing testable Xray capability detector'
Check-Contains 'freedom.sh' 'printf .*tls-ping' 'freedom.sh must detect missing xray tls ping support separately'
Check-Contains 'freedom.sh' '--update-xray' 'freedom.sh missing explicit official Xray update option'
Check-Contains 'freedom.sh' 'FREEDOM_UPDATE_XRAY=' 'freedom.sh missing Xray update environment option'
Check-Contains 'freedom.sh' 'write_xray_config\(\)' 'freedom.sh missing Xray config writer'
Check-Contains 'freedom.sh' 'preflight_check\(\)' 'freedom.sh missing read-only preflight check'
Check-Contains 'freedom.sh' 'validate_domain_name\(\)' 'freedom.sh missing SNI domain validator'
Check-Contains 'freedom.sh' 'probe_sni_domain\(\)' 'freedom.sh missing SNI reachability probe'
Check-Contains 'freedom.sh' 'check_reality_target_asn\(\)' 'freedom.sh missing read-only REALITY target ASN comparison'
Check-Contains 'freedom.sh' 'https://api\.ip\.sb/geoip/' 'freedom.sh ASN comparison must use an explicit HTTPS lookup endpoint'
Check-Contains 'freedom.sh' '--skip-asn-check' 'freedom.sh missing ASN check bypass option'
Check-Contains 'freedom.sh' 'openssl s_client' 'freedom.sh SNI probe must use openssl s_client for TLS capability checks'
Check-Contains 'freedom.sh' '-tls1_3' 'freedom.sh SNI probe must explicitly test TLS 1.3 support'
Check-Contains 'freedom.sh' '-alpn h2,http/1\.1' 'freedom.sh SNI probe must explicitly test ALPN/H2 support'
Check-Contains 'freedom.sh' 'ALPN protocol: h2' 'freedom.sh SNI probe must recognize negotiated HTTP/2'
Check-Contains 'freedom.sh' 'SNI_CHECK=' 'freedom.sh missing SNI check toggle'
Check-Contains 'freedom.sh' '--skip-sni-check' 'freedom.sh missing SNI check bypass option'
Check-Contains 'freedom.sh' 'validate_link_host\(\)' 'freedom.sh missing server/link host validator'
Check-Contains 'freedom.sh' 'host:port is not accepted' 'freedom.sh must reject server host:port inputs'
Check-Contains 'freedom.sh' 'validate_domain_name "\$host"' 'freedom.sh server host validator must accept only valid domain names for hostname input'
Check-Contains 'freedom.sh' 'ip_to_int "\$host"' 'freedom.sh server host validator must validate IPv4 input'
Check-Contains 'freedom.sh' 'validate_ipv6_literal\(\)' 'freedom.sh missing IPv6 literal validator'
Check-Contains 'freedom.sh' 'local -a left_parts right_parts parts' 'freedom.sh IPv6 validator must keep arrays local'
Check-Contains 'freedom.sh' 'validate_ipv6_literal "\$host"' 'freedom.sh server host validator must use IPv6 literal validator'
Check-Contains 'freedom.sh' 'return 1 # malformed hostname' 'freedom.sh server host validator must reject malformed hostnames'
Check-Contains 'freedom.sh' 'ip_to_int\(\)' 'freedom.sh missing IPv4 integer conversion helper'
Check-Contains 'freedom.sh' '10#\$a' 'freedom.sh IPv4 parsing must force decimal arithmetic'
Check-Contains 'freedom.sh' 'ip_in_range\(\)' 'freedom.sh missing IPv4 CIDR range helper'
Check-Contains 'freedom.sh' 'ip_in_range "\$ip_num"' 'freedom.sh private/local IPv4 detection must use numeric ranges'
Check-Contains 'freedom.sh' 'is_private_or_local_ip\(\)' 'freedom.sh missing private/local IP detector'
Check-Contains 'freedom.sh' 'auto_detected_server=1' 'freedom.sh must track auto-detected server address'
Check-Contains 'freedom.sh' 'is_private_or_local_ip "\$SERVER_IP"' 'freedom.sh must reject private/local auto-detected server addresses'
Check-Contains 'freedom.sh' '2001:db8' 'freedom.sh must treat IPv6 documentation addresses as non-public'
Check-Contains 'freedom.sh' 'first_value >= 16#ff00 && first_value <= 16#ffff' 'freedom.sh must treat IPv6 multicast addresses as non-public'
Check-Contains 'freedom.sh' 'secure_config_permissions\(\)' 'freedom.sh missing secure config permissions helper'
Check-Contains 'freedom.sh' 'download_and_run_installer\(\)' 'freedom.sh missing safer installer runner'
Check-Contains 'freedom.sh' '--xray-encryption' 'freedom.sh missing Xray encryption CLI option'
Check-Contains 'freedom.sh' 'XRAY_ENCRYPTION_CHOICE="\$\{FREEDOM_XRAY_ENCRYPTION:-x25519\}"' 'freedom.sh must default VLESS Encryption auth to X25519'
Check-Contains 'freedom.sh' 'extract_vlessenc_value\(\)' 'freedom.sh must select X25519 or ML-KEM-768 auth from xray vlessenc output'
Check-Contains 'freedom.sh' 'alg="X25519"' 'freedom.sh must support X25519 auth selection'
Check-Contains 'freedom.sh' 'alg="ML-KEM-768"' 'freedom.sh must support ML-KEM-768 auth selection'
Check-Contains 'freedom.sh' 'extract_vlessenc_value "\$out" "\$alg" "decryption"' 'freedom.sh must extract selected auth decryption from xray vlessenc output'
Check-Contains 'freedom.sh' 'extract_vlessenc_value "\$out" "\$alg" "encryption"' 'freedom.sh must extract selected auth encryption from xray vlessenc output'
Check-Contains 'freedom.sh' 'xray_tls_ping_probe\(\)' 'freedom.sh missing official xray tls ping SNI probe'
Check-Contains 'freedom.sh' 'tls ping "\$host"' 'freedom.sh SNI probe should prefer official xray tls ping'
Check-Contains 'freedom.sh' 'generate_spider_x\(\)' 'freedom.sh missing randomized REALITY spiderX generator'
Check-Contains 'freedom.sh' 'validate_mldsa_target\(\)' 'freedom.sh must validate REALITY target suitability before enabling ML-DSA'
Check-Contains 'freedom.sh' 'chain_length <= 3500' 'freedom.sh must reject undersized REALITY target chains for ML-DSA'
Check-Contains 'freedom.sh' 'TLS Post-Quantum key exchange:' 'freedom.sh must report whether the REALITY target supports post-quantum key exchange'
Check-Contains 'freedom.sh' 'token="\$\(gen_uuid' 'freedom.sh spiderX randomness should prefer official xray uuid generator'
Check-Contains 'freedom.sh' 'SPIDER_X=' 'freedom.sh missing spiderX state'
Check-Contains 'freedom.sh' 'encoded_spider_x="\$\(url_encode "\$SPIDER_X"\)"' 'freedom.sh share link must URL-encode generated spiderX'
Check-Contains 'freedom.sh' 'spx=\$\{encoded_spider_x\}' 'freedom.sh share link must use generated spiderX'
Check-Contains 'freedom.sh' 'network: "raw"' 'freedom.sh REALITY transport should use official raw network'
Check-Contains 'freedom.sh' 'type=raw' 'freedom.sh share link must use raw network'
Check-NotContains 'freedom.sh' 'network: "tcp"' 'freedom.sh should not use legacy tcp network spelling for REALITY'
Check-NotContains 'freedom.sh' 'type=tcp' 'freedom.sh share link should not use legacy tcp type'
Check-NotContains 'freedom.sh' 'spx=%2F' 'freedom.sh should not pin spiderX to root path'
Check-Contains 'freedom.sh' '--check, --preflight' 'freedom.sh missing read-only preflight CLI option'
Check-Contains 'freedom.sh' 'clear_screen\(\)' 'freedom.sh missing non-interactive clear guard'
Check-Contains 'freedom.sh' 'listener_protocol\(\)' 'freedom.sh missing listener protocol selector'
Check-Contains 'freedom.sh' 'port_listener_summary "\$PORT" "\$proto"' 'freedom.sh port checks must honor TCP/UDP listener protocol'
Check-Contains 'freedom.sh' 'ss -H -lunp "sport = :\$\{port\}"' 'freedom.sh H3 listener checks must inspect UDP sockets'
Check-Contains 'freedom.sh' 'verify_service_port_listening\(\)' 'freedom.sh missing post-restart port listener verification'
Check-Contains 'freedom.sh' 'verify_service_port_listening' 'freedom.sh restart flow must verify the service port is listening'
Check-Contains 'freedom.sh' 'not listening on \$\{proto\^\^\} port' 'freedom.sh must report missing post-restart listener using the expected protocol'
Check-Contains 'freedom.sh' 'Xray config install failed' 'freedom.sh must handle config install failures explicitly'
Check-Contains 'freedom.sh' 'umask 077' 'freedom.sh must protect temporary files containing private key material'
Check-Contains 'freedom.sh' 'install_generated_config_atomically\(\)' 'freedom.sh missing atomic generated-config installer'
Check-Contains 'freedom.sh' 'if ! install_generated_config_atomically "\$tmp"; then' 'freedom.sh config install must not rely on errexit'
Check-Contains 'freedom.sh' 'mv -f -- "\$tmp" "\$CONFIG_PATH"' 'freedom.sh must replace generated config atomically within its directory'
Check-Contains 'freedom.sh' 'fallback: xray -test -config' 'freedom.sh config validation must preserve fallback test diagnostics'
Check-Contains 'freedom.sh' 'usage_error\(\)' 'freedom.sh missing CLI usage error helper'
Check-Contains 'freedom.sh' 'require_option_value\(\)' 'freedom.sh missing CLI option value validator'
Check-Contains 'freedom.sh' 'require_option_value "--sni"' 'freedom.sh CLI must validate --sni values'
Check-Contains 'freedom.sh' 'require_option_value "--xray-encryption"' 'freedom.sh CLI must validate --xray-encryption values'
Check-Contains 'freedom.sh' '--mode MODE' 'freedom.sh missing deployment mode CLI option'
Check-Contains 'freedom.sh' '--cdn-xhttp-tls' 'freedom.sh missing CDN XHTTP TLS shortcut option'
Check-Contains 'freedom.sh' 'Deployment profile: 1=REALITY-VISION \(direct\), 2=XHTTP-TLS-VISION \(CDN\)' 'freedom.sh deployment prompt should use polished uppercase profile names'
Check-Contains 'freedom.sh' 'FREEDOM_MODE=reality\|cdn-xhttp-tls' 'freedom.sh missing deployment mode environment option'
Check-Contains 'freedom.sh' 'FREEDOM_XHTTP_PATH=' 'freedom.sh missing XHTTP path environment option'
Check-Contains 'freedom.sh' 'FREEDOM_XHTTP_PROFILE=' 'freedom.sh missing XHTTP transport profile environment option'
Check-Contains 'freedom.sh' 'FREEDOM_ROUTE_PROFILE=' 'freedom.sh missing routing profile environment option'
Check-Contains 'freedom.sh' 'FREEDOM_TLS_CERT_FILE=' 'freedom.sh missing TLS certificate environment option'
Check-Contains 'freedom.sh' 'FREEDOM_TLS_KEY_FILE=' 'freedom.sh missing TLS key environment option'
Check-Contains 'freedom.sh' 'FREEDOM_TLS_CERT_MODE=' 'freedom.sh missing TLS certificate mode environment option'
Check-Contains 'freedom.sh' 'normalize_deploy_mode\(\)' 'freedom.sh missing deployment mode normalizer'
Check-Contains 'freedom.sh' 'normalize_tls_cert_mode\(\)' 'freedom.sh missing TLS certificate mode normalizer'
Check-Contains 'freedom.sh' 'normalize_xhttp_transport_profile\(\)' 'freedom.sh missing XHTTP transport profile normalizer'
Check-Contains 'freedom.sh' 'warn_cloudflare_origin_ca_scope\(\)' 'freedom.sh missing reusable Cloudflare Origin CA warning helper'
Check-Contains 'freedom.sh' 'Cloudflare Origin CA requires Cloudflare proxy with Full\(strict\)' 'freedom.sh must clearly explain Cloudflare Origin CA trust scope'
Check-Contains 'freedom.sh' 'CDN mode defaults the share address to the TLS/SNI domain' 'freedom.sh CDN mode must avoid defaulting share links to the origin IP'
Check-Contains 'freedom.sh' 'Use --server for a preferred CDN IP or hostname' 'freedom.sh CDN mode must explain explicit CDN share address override'
Check-Contains 'freedom.sh' 'CDN XHTTP TLS mode will default the share address to the TLS/SNI domain' 'freedom.sh preflight must preview CDN share address default'
Check-Contains 'freedom.sh' 'REALITY target SNI or XHTTP-TLS certificate/SNI domain' 'freedom.sh help must describe SNI semantics for both deploy modes'
Check-Contains 'freedom.sh' 'In XHTTP-TLS mode, omit this to use SNI; set it for preferred CDN IP/hostname' 'freedom.sh help must explain CDN mode --server semantics'
Check-Contains 'freedom.sh' 'Certificate profile: 1=PUBLIC CA, 2=CLOUDFLARE ORIGIN CA' 'freedom.sh TLS certificate prompt must support polished numeric choices'
Check-Contains 'freedom.sh' 'Transport profile: 1=CDN-STABLE, 2=CDN-H2, 3=CDN-H3' 'freedom.sh transport prompt must separate CDN edge ALPN from origin ALPN'
Check-NotContains 'freedom.sh' 'Transport profile: 1=CDN-STABLE, 2=CDN-H2, 3=CDN-H3, 4=DIRECT-H3' 'freedom.sh normal transport prompt must not advertise direct H3'
Check-Contains 'freedom.sh' 'CDN-H3 keeps the Xray origin on TCP H1/H2' 'freedom.sh must explain CDN H3 origin conversion'
Check-Contains 'freedom.sh' 'DIRECT-H3 makes Xray listen on UDP' 'freedom.sh help/preflight must warn about direct Xray H3'
Check-Contains 'freedom.sh' 'enforce_reality_port_policy\(\)' 'freedom.sh missing REALITY port policy helper'
Check-Contains 'freedom.sh' '--allow-nonstandard-reality-port' 'freedom.sh missing explicit non-443 REALITY override'
Check-Contains 'freedom.sh' 'REALITY is expected to listen on TCP/443' 'freedom.sh must explain the non-443 REALITY risk'
Check-Contains 'freedom.sh' 'validate_xhttp_path\(\)' 'freedom.sh missing XHTTP path validator'
Check-Contains 'freedom.sh' 'xhttp_origin_alpn_json\(\)' 'freedom.sh missing XHTTP origin ALPN helper'
Check-Contains 'freedom.sh' 'xhttp_client_alpn_json\(\)' 'freedom.sh missing XHTTP client ALPN helper'
Check-Contains 'freedom.sh' 'check_tls_cert_files\(\)' 'freedom.sh missing non-fatal TLS certificate checker'
Check-Contains 'freedom.sh' 'validate_tls_cert_files\(\)' 'freedom.sh missing fatal TLS certificate validation wrapper'
Check-Contains 'freedom.sh' 'openssl is required to validate TLS certificate files' 'freedom.sh TLS certificate checker must fail clearly when openssl is missing'
Check-Contains 'freedom.sh' 'check_tls_cert_files "\$SNI" \|\| fatal "TLS certificate validation failed"' 'freedom.sh deploy-time TLS cert validator must pass SNI explicitly'
Check-Contains 'freedom.sh' 'check_tls_cert_files "\$sni" \|\| failures=\$\(\(failures \+ 1\)\)' 'freedom.sh preflight must pass its local SNI to certificate checks'
Check-Contains 'freedom.sh' 'cert_covers_domain\(\)' 'freedom.sh missing TLS certificate SAN/CN coverage checker'
Check-Contains 'freedom.sh' 'openssl x509 -in "\$cert_file" -noout -checkhost "\$domain"' 'freedom.sh certificate hostname checks must honor SAN precedence'
Check-Contains 'freedom.sh' 'check_tls_files_service_readable\(\)' 'freedom.sh must verify the Xray service account can read TLS files'
Check-Contains 'freedom.sh' 'cloudflare_https_port_supported\(\)' 'freedom.sh missing Cloudflare HTTPS port validation'
Check-Contains 'freedom.sh' 'openssl x509 -checkend 0 -noout -in "\$TLS_CERT_FILE"' 'freedom.sh must reject expired TLS certificates'
Check-Contains 'freedom.sh' 'TLS private key does not match certificate' 'freedom.sh must reject TLS key/certificate mismatches'
Check-Contains 'freedom.sh' 'TLS certificate does not cover SNI domain' 'freedom.sh must verify certificate covers the configured SNI domain'
Check-Contains 'freedom.sh' 'TLS certificate expires within 14 days' 'freedom.sh should warn before near-expiring TLS certificates'
Check-Contains 'freedom.sh' 'write_xray_config_xhttp_tls\(\)' 'freedom.sh missing XHTTP TLS config writer'
Check-Contains 'freedom.sh' 'network: "xhttp"' 'freedom.sh CDN mode must use XHTTP network'
Check-Contains 'freedom.sh' 'security: "tls"' 'freedom.sh CDN mode must use TLS security'
Check-Contains 'freedom.sh' 'rejectUnknownSni: true' 'freedom.sh CDN TLS mode must reject SNI values not covered by its certificate'
Check-Contains 'freedom.sh' 'minVersion: "1\.2"' 'freedom.sh CDN TLS mode must reject TLS versions older than 1.2'
Check-Contains 'freedom.sh' 'maxVersion: "1\.3"' 'freedom.sh CDN TLS mode must cap TLS at the supported 1.3 version'
Check-Contains 'freedom.sh' 'xhttpSettings' 'freedom.sh CDN mode missing xhttpSettings'
Check-Contains 'freedom.sh' 'certificateFile: \$tls_cert_file' 'freedom.sh CDN mode must use certificate file paths'
Check-Contains 'freedom.sh' 'keyFile: \$tls_key_file' 'freedom.sh CDN mode must use key file paths'
Check-Contains 'freedom.sh' 'clients: \[ \{ id: \$uuid, flow: "xtls-rprx-vision" \} \]' 'freedom.sh CDN mode must enable Vision flow with modern VLESS Encryption/XHTTP'
Check-Contains 'freedom.sh' 'type=xhttp' 'freedom.sh CDN share link must use XHTTP type'
Check-Contains 'freedom.sh' 'security=tls' 'freedom.sh CDN share link must use TLS security'
Check-Contains 'freedom.sh' 'mode=auto' 'freedom.sh CDN share link should use XHTTP auto mode'
Check-Contains 'freedom.sh' 'alpn=\$\{encoded_alpn\}&flow=xtls-rprx-vision&encryption=' 'freedom.sh CDN share link must advertise Vision flow'
Check-Contains 'freedom.sh' 'Cloudflare Origin CA requires Cloudflare proxy with Full\(strict\)' 'freedom.sh must warn about Cloudflare Origin CA trust scope'
Check-Contains 'freedom.sh' 'validate_generated_config "\$tmp"' 'freedom.sh must validate generated temp config before installing it'
Check-Contains 'freedom.sh' 'mktemp --suffix=\.json "\$\{CONFIG_DIR\}/config\.tmp\.XXXXXX"' 'freedom.sh generated Xray temp configs must retain a .json suffix'
Check-NotContains 'freedom.sh' 'config\.json\.tmp\.XXXXXX' 'freedom.sh must not use temp config names whose final extension is unknown to Xray'
Check-Contains 'freedom.sh' '"\$BIN" run -test -c "\$config_file"' 'freedom.sh temp config validation must use xray run -test before install'
Check-Contains 'freedom.sh' 'H2 is recommended, not mandatory' 'freedom.sh must treat missing H2 as a warning instead of a hard failure'
Check-NotContains 'freedom.sh' '\[\[ "\$tls_ok" -ne 1 \|\| "\$h2_ok" -ne 1 \]\]' 'freedom.sh must not require H2 for SNI usability'
Check-Contains 'freedom.sh' '\{"type":"field","ip":\["geoip:private"\],"outboundTag":"block"\}' 'freedom.sh route must block private IP first'
Check-Contains 'freedom.sh' '\{"type":"field","protocol":\["bittorrent"\],"outboundTag":"block"\}' 'freedom.sh route must block bittorrent traffic through Xray'
Check-Contains 'freedom.sh' '\{"type":"field","domain":\["geosite:cn"\],"outboundTag":"block"\}' 'freedom.sh route must block CN domains'
Check-Contains 'freedom.sh' '\{"type":"field","ip":\["geoip:cn"\],"outboundTag":"block"\}' 'freedom.sh route must block CN IP'
Check-NotContains 'freedom.sh' '\{"type":"field","domain":\["geosite:geolocation-!cn"\],"outboundTag":"direct"\}' 'freedom.sh should rely on default direct instead of explicit geolocation-!cn direct'
Check-NotContains 'freedom.sh' '\{"type":"field","ip":\["geoip:private","geoip:cn"\],"outboundTag":"block"\}' 'freedom.sh route must keep private and CN IP blocks ordered separately'
Check-Contains 'freedom.sh' 'routing_domain_strategy\(\)' 'freedom.sh missing routing strategy profile helper'
Check-Contains 'freedom.sh' 'IPIfNonMatch' 'freedom.sh strict routing profile must resolve unmatched domains for IP rules'
Check-Contains 'freedom.sh' 'Non-interactive failure; restoring the previous configuration automatically' 'freedom.sh must rollback safely when stdin is unavailable'
Check-Contains 'freedom.sh' 'Fresh deployment failed; removing the new configuration' 'freedom.sh must clean up a failed first deployment'
Check-Contains 'freedom.sh' 'decryption\|encryption\|privateKey\|mldsa65Seed' 'freedom.sh diagnostic redaction must cover generated authentication secrets'

Check-NotContains 'freedom.sh' 'sing-box|singbox|--kernel|FREEDOM_KERNEL|write_singbox_config|install_singbox_official|gen_reality_keys_singbox|choose_kernel' 'freedom.sh still contains sing-box/core-selection support'
Check-NotContains 'freedom.sh' 'BLOCK_CN=' 'freedom.sh must not keep an unused routing toggle when CN blocking is unconditional'
Check-NotContains 'freedom.sh' '> "\$CONFIG_PATH"' 'freedom.sh must write config atomically instead of truncating config path directly'
Check-NotContains 'freedom.sh' 'chmod 644 "\$CONFIG_PATH"' 'freedom.sh must not make Xray config world-readable'
Check-NotContains 'freedom.sh' '/tmp/freedom-' 'freedom.sh must not use predictable /tmp log paths'
Check-NotContains 'freedom.sh' 'curl .*[|] sh' 'freedom.sh must not pipe installer downloads to sh'
Check-NotContains 'freedom.sh' 'bash -c "\$\(curl' 'freedom.sh must not execute downloaded installer inline'
Check-NotContains 'freedom.sh' 'xargs -r rm -f' 'freedom.sh backup cleanup must not use ls/xargs deletion'
Check-NotContains 'freedom.sh' 'systemctl enable xray >/dev/null 2>&1 \|\| true' 'freedom.sh must not hide Xray enable failures after installation'
Check-Contains 'freedom.sh' 'systemctl enable xray >/dev/null 2>&1 \|\| fatal "Xray service enable failed"' 'freedom.sh must fail clearly when Xray service enable fails'

$bashVerified = $false
$wsl = Get-Command wsl.exe -ErrorAction SilentlyContinue
if ($null -ne $wsl) {
  & $wsl.Source --cd (Get-Location).Path -- bash -lc 'command -v bash >/dev/null 2>&1' 2>$null
  if ($LASTEXITCODE -eq 0) {
    & $wsl.Source --cd (Get-Location).Path -- bash verify.sh
    if ($LASTEXITCODE -ne 0) {
      exit $LASTEXITCODE
    }
    $bashVerified = $true
  }
}

if (-not $bashVerified) {
  $bashCandidates = @(Get-Command bash -All -ErrorAction SilentlyContinue | Where-Object {
    $_.Source -notlike '*\System32\bash.exe' -and $_.Source -notlike '*\WindowsApps\bash.exe'
  })
  $git = Get-Command git -ErrorAction SilentlyContinue
  if ($null -ne $git) {
    $gitRoot = Split-Path (Split-Path $git.Source -Parent) -Parent
    foreach ($candidate in @((Join-Path $gitRoot 'bin\bash.exe'), (Join-Path $gitRoot 'usr\bin\bash.exe'))) {
      if (Test-Path -LiteralPath $candidate) {
        $bashCandidates += Get-Item -LiteralPath $candidate
      }
    }
  }
  $bashCandidate = $bashCandidates | Select-Object -First 1
  if ($null -ne $bashCandidate) {
    & $bashCandidate.FullName verify.sh
    if ($LASTEXITCODE -ne 0) {
      exit $LASTEXITCODE
    }
    $bashVerified = $true
  }
}

if (-not $bashVerified) {
  Write-Host '[WARN] usable WSL/Git Bash not found; skipped Bash runtime checks.'
}

Write-Host '[OK] verification passed'
